# -*- coding: utf-8 -*-
"""Assignment3_Part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hSp05e3WW5dWz-81j649wseTma7l1HVw
"""

import numpy as np
import os
import math
import random
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve
from sklearn.metrics import det_curve

"""**Part A : K-means clustering and GMM**"""

from google.colab import drive
drive.mount('/content/drive')

## Reading file into a numpy array
x1_train,x2_train,t_train = np.loadtxt("/content/train.txt", delimiter=',', unpack=True)
x1_dev,x2_dev,t_dev = np.loadtxt("/content/dev.txt", delimiter=',', unpack=True)

mean_train1 = np.mean(x1_train)
std_train1 = np.std(x1_train)

mean_train2 = np.mean(x2_train)
std_train2 = np.std(x2_train)

mean_dev1 = np.mean(x1_dev)
std_dev1 = np.std(x1_dev)

mean_dev2 = np.mean(x2_dev)
std_dev2 = np.std(x2_dev)

for n in range(len(x1_train)):
  x1_train[n] = (x1_train[n]-mean_train1)/std_train1
  x2_train[n] = (x2_train[n]-mean_train2)/std_train2

for n in range(len(x1_dev)):
  x1_dev[n] = (x1_dev[n]-mean_dev1)/std_dev1
  x2_dev[n] = (x2_dev[n]-mean_dev2)/std_dev2

x_train = [x1_train,x2_train]
x_train = np.asarray(x_train)
x_train = x_train.T

x_dev = [x1_dev,x2_dev]
x_dev = np.asarray(x_dev)
x_dev = x_dev.T

half_train_size = 1250
half_dev_size = 500

x_train_classwise = [x_train[:half_train_size,:],x_train[half_train_size:,:]]
x_train_classwise = np.asarray(x_train_classwise)

x_dev_classwise = [x_dev[:half_dev_size,:],x_dev[half_dev_size:,:]]
x_dev_classwise = np.asarray(x_dev_classwise)

## Reading file into a numpy array

Train_data = []
Dev_data = []

X=[]
os.chdir('/content/drive/MyDrive/Features/coast/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/coast/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/coast/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/coast/train'}/{file}" 
    Y.append(np.loadtxt(file_path)) 
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/forest/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/forest/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/forest/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/forest/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/highway/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/highway/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/highway/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/highway/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/mountain/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/mountain/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/mountain/train')
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/mountain/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/opencountry/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/opencountry/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/opencountry/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/opencountry/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

Train_data1 = []
for clas in Train_data:
  for v in clas:
    Train_data1.append(v)

Dev_data1 = []
for clas in Dev_data:
  for v in clas:
    Dev_data1.append(v)

Train_data2 = []
for clas in Train_data:
  temp=[]
  for image in clas:
    for v in image:
      temp.append(v)
  Train_data2.append(temp)

Dev_data2 = []
for clas in Dev_data:
  temp=[]
  for image in clas:
    for v in image:
      temp.append(v)
  Dev_data2.append(temp)

# K-means algorithm
def K_means(X,Z,runs): 
  N = len(X) 
  K = len(Z)
  d = len(X[0])
  r = np.zeros(N) 
  for run in range(runs):
    for n in range(N):
      dist = np.inf
      cluster = -1
      for k in range(K):
        if np.linalg.norm(X[n]-Z[k]) < dist:
          dist = np.linalg.norm(X[n]-Z[k])
          cluster = k
        elif np.linalg.norm(X[n]-Z[k]) == dist:
          if random.randint(0,1) == 1:
            cluster = k
      r[n] = cluster
    for k in range(K):
      sum = np.zeros(d)
      cnt = 0
      for n in range(N):
        if r[n]==k:
          sum += X[n]
          cnt += 1  
      Z[k] = sum/cnt 
  return Z,r

def Multivariate_Gaussian1(pos, mu, Sigma):
  """Return the multivariate Gaussian distribution on array pos.

  pos is an array constructed by packing the meshed arrays of variables
  x_1, x_2, x_3, ..., x_k into its last dimension.

  """
    
  n = mu.shape[0]
  Sigma_det = np.linalg.det(Sigma)
  Sigma_inv = np.linalg.inv(Sigma)
  N = np.sqrt((2*np.pi)**n * Sigma_det)
  # This einsum call calculates (x-mu)T.Sigma-1.(x-mu) in a vectorized
  # way across all the input variables.
  fac = np.einsum('...k,kl,...l->...', pos-mu, Sigma_inv, pos-mu)

  return np.exp(-fac / 2) / N

# Computes the multivariate gaussian function's value at point "x"
def Multivariate_Gaussian(x,mu,sigma):
    n = len(mu)
    x = np.reshape(x,(n,1))
    mu = np.reshape(mu,(n,1))
    sigma_det = np.linalg.det(sigma)
    sigma_inv = np.linalg.inv(sigma)
    denom = np.sqrt(((2*np.pi)**n)*sigma_det)
    fac = ((x-mu).T)@(sigma_inv)@(x-mu)
    return np.exp(-fac/2)/denom

# No of data points belonging to the kth cluster
def Cnt(X,k,r):
  N = len(X) 
  cnt = 0
  for n in range(N):
    if r[n] == k:
      cnt += 1
  return cnt

# Computation of mixing coefficients of GMM
def Pi(k,N,gamma):
  sum = 0
  for n in range(N):
      sum += gamma[n,k]
  return sum/N

# Computation of means of the mixtures of GMM
def Mu(X,N,k,gamma):
  sum = np.zeros(len(X[0]))
  cnt = 0
  for n in range(N):
      sum += X[n]*gamma[n,k]
      cnt += gamma[n,k]
  return sum/cnt

# Covariance matrix estimation for kth cluster
def Sigma1(X,k,r,mu):
  N = len(X) 
  d = len(mu)
  X = np.reshape(X,(N,d,1))
  mu = np.reshape(mu,(d,1))
  sum = np.zeros((d,d))
  cnt = 0
  for n in range(N):
    if r[n] == k:
      sum += (X[n]-mu)@((X[n]-mu).T)
      cnt += 1
  return sum/cnt

# Covariance matrix estimation for kth mixture of GMM
def Sigma2(X,k,mu,gamma):
  N = len(X)
  d = len(mu)
  X = np.reshape(X,(N,d,1))
  mu = np.reshape(mu,(d,1))
  sum = np.zeros((d,d))
  cnt = 0 
  for n in range(N):
    sum += gamma[n,k]*((X[n]-mu)@((X[n]-mu).T))
    cnt += gamma[n,k]
  return sum/cnt

# Computation of responsibilities of GMM
def Gamma(x,k,pi,mu,sigma):
  sum = 0
  K = len(pi)
  for i in range(K):
    sum += pi[i]*Multivariate_Gaussian(x,mu[i],sigma[i])
  return (pi[k]*Multivariate_Gaussian(x,mu[k],sigma[k]))/sum

# EMM algorithm (for GMMs)
def EM(X,Z,runs1,runs2):    
  N = len(X) 
  K = len(Z)
  mu,r = K_means(X,Z,runs1)
  pi = np.zeros(K)
  sigma = np.zeros((K,len(X[0]),len(X[0])))
  gamma = np.zeros((N,K))
  for k in range(K):
    sigma[k] = Sigma1(X,k,r,mu[k])
    pi[k] = Cnt(X,k,r)/N
  for run in range(runs2):
    for n in range(N):
      for k in range(K):
        gamma[n,k] = Gamma(X[n],k,pi,mu,sigma)
    for k in range(K):
      pi[k] = Pi(k,N,gamma)
      mu[k] = Mu(X,N,k,gamma)
      sigma[k] = Sigma2(X,k,mu[k],gamma)
  return pi,mu,sigma

# EMM algorithm (for GMMs)
# def EM_diag(X,Z,runs1,runs2):    
#   N = len(X) 
#   K = len(Z)
#   mu,r = K_means(X,Z,runs1)
#   pi = np.zeros(K)
#   sigma = np.zeros((K,len(X[0]),len(X[0])))
#   # for k in range(K):
#   #   for i in range(len(X[0])):
#   #     for j in range(len(X[0])):
#   #       if i!=j:
#   #         sigma[k][i][j] = 0
#   gamma = np.zeros((N,K))
#   for k in range(K):
#     sigma[k] = Sigma1(X,k,r,mu[k])
#     for k in range(K):
#       for i in range(len(X[0])):
#         for j in range(len(X[0])):
#           if i!=j:
#             sigma[k][i][j] = 0
#     pi[k] = Cnt(X,k,r)/N
#   for run in range(runs2):
#     for n in range(N):
#       for k in range(K):
#         gamma[n,k] = Gamma(X[n],k,pi,mu,sigma)
#     for k in range(K):
#       pi[k] = Pi(k,N,gamma)
#       mu[k] = Mu(X,N,k,gamma)
#       sigma[k] = Sigma2(X,k,mu[k],gamma)
#   for k in range(K):
#         for i in range(len(X[0])):
#           for j in range(len(X[0])):
#             if i!=j:
#               sigma[k][i][j] = 0
#   return pi,mu,sigma

# Computes the gaussian mixture's value at point "x"
def Gaussian_mixture(x,pi,mu,sigma):
  sum = 0
  K = len(pi)
  for k in range(K):
    sum += pi[k]*Multivariate_Gaussian(x,mu[k],sigma[k])
  return sum

K1 = 3

Z1 = x_dev_classwise[0][np.random.choice(range(x_dev_classwise[0].shape[0]),replace=False,size=K1)]
# Z1 = random_partition(X_train[0],K1)

runs11 = 5
runs12 = 10

pi1,mu1,sigma1 = EM(x_dev_classwise[0],Z1,runs11,runs12)
# pi_diag_1,mu_diag_1,sigma_diag_1 = EM_diag(x_train_classwise[0],Z1,runs11,runs12)

K2 = 3

Z2 = x_dev_classwise[1][np.random.choice(range(x_dev_classwise[1].shape[0]),replace=False,size=K2)]
# Z2 = random_partition(X_train[1],K2)

runs21 = 5
runs22 = 10

pi2,mu2,sigma2 = EM(x_dev_classwise[1],Z2,runs21,runs22)
# pi_diag_2,mu_diag_2,sigma_diag_2 = EM_diag(x_train_classwise[1],Z2,runs21,runs22)

pi = [pi1,pi2]
mu = [mu1,mu2]
sigma = [sigma1,sigma2]

X = np.linspace(-3,3,num=2000)
Y = np.linspace(-3,3,num=2000)
X, Y = np.meshgrid(X, Y)
pos = np.empty(X.shape + (2,))
pos[:, :, 0] = X
pos[:, :, 1] = Y
Z = []
for i in range(2):
  for j in range(len(mu[0])):
    Z = pi[i][j]*Multivariate_Gaussian1(pos,mu[i][j],sigma[i][j])
    plt.contour(X,Y,Z,levels=[0.005,0.01,0.025,0.037,0.075,0.08,0.1,0.15,0.2])

plt.scatter(x1_dev,x2_dev)

N = len(x_dev)
C = 2
S = np.zeros((N,C))
  
for n in range(N):
  for c in range(C):
    S[n,c] = Gaussian_mixture(x_dev[n],pi[c],mu[c],sigma[c])/2

min = np.amin(S)
max = np.amax(S)

TPR = []
FPR = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S[i,j] >= threshold:
        if t_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if t_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR.append(TP/(TP+FN))  # True positive rate
  FPR.append(FP/(FP+TN))  # False positive rate

# plotting
# plt.title("ROC curve")
# plt.xlabel("False Positive Rate")
# plt.ylabel("True Positive Rate")
# plt.plot(FPR, TPR, color ="green")
# plt.show()

FNR = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S[i,j] >= threshold:
        if t_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if t_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  FNR.append(FN/(TP+FN))  # False negative rate

# plotting
# plt.title("DET curve")
# plt.xlabel("False Alarm Rate")
# plt.ylabel("Missed Detection Rate")
# plt.plot(FPR, FNR, color ="red")
# plt.show()

sigma_diag = []

for i in range(2):
  cov1 = []
  for cov in sigma[i]:
    size = len(cov)
    temp = cov
    for i in range(size):
      for j in range(size):
        if i!=j:
          temp[i][j] = 0
    cov1.append(temp)
  sigma_diag.append(cov1)

S_diag = np.zeros((N,C)) 

for n in range(N):
  for c in range(C):
    S_diag[n,c] = Gaussian_mixture(x_dev[n],pi[c],mu[c],sigma_diag[c])/2

min = np.amin(S_diag)
max = np.amax(S_diag)

TPR_diag = []
FPR_diag = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S_diag[i,j] >= threshold:
        if t_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if t_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR_diag.append(TP/(TP+FN))  # True positive rate
  FPR_diag.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR_diag,TPR_diag,color='red',label='Diagonal covariance')
plt.plot(FPR,TPR,color='blue',label='Non-diagonal covariance')
  
# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

# plotting
# plt.title("ROC curve")
# plt.xlabel("False Positive Rate")
# plt.ylabel("True Positive Rate")
# plt.plot(FPR_diag, TPR_diag, color ="green")
# plt.show()

FNR_diag = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S_diag[i,j] >= threshold:
        if t_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if t_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  FNR_diag.append(FN/(TP+FN))  # False negative rate

plt.plot(FPR_diag,FNR_diag,color='pink',label='Diagonal covariance')
plt.plot(FPR,FNR,color='green',label='Non-diagonal covariance')
  
# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

# plotting
# plt.title("DET curve")
# plt.xlabel("False Alarm Rate")
# plt.ylabel("Missed Detection Rate")
# plt.plot(FPR, FNR, color ="red")
# plt.show()

"""**Image Dataset**"""

# [0,250]
# [251,479]
# [480,661]
# [662,922]
# [923,1209]
def groundtruth_train(i):
  if i<=250:
    return 1
  elif i<=479:
    return 2
  elif i<=661:
    return 3
  elif i<=922:
    return 4
  else:
    return 5

# [0,72]
# [73,138]
# [53,190]
# [191,274]
# [275,356]
def groundtruth_dev(i):
  if i<=72:
    return 1
  elif i<=138:
    return 2
  elif i<=190:
    return 3
  elif i<=274:
    return 4
  else:
    return 5

K1 = 4

temp = np.asarray(Dev_data2[0])

Z1 = temp[np.random.choice(range(temp.shape[0]),replace=False,size=K1)]

runs11 = 5
runs12 = 15

pi1,mu1,sigma1 = EM(temp,Z1,runs11,runs12)

K2 = 4

temp = np.asarray(Dev_data2[1])

Z2 = temp[np.random.choice(range(temp.shape[0]),replace=False,size=K2)]

runs21 = 5
runs22 = 15

pi2,mu2,sigma2 = EM(temp,Z2,runs21,runs22)

K3 = 4

temp = np.asarray(Dev_data2[2])

Z3 = temp[np.random.choice(range(temp.shape[0]),replace=False,size=K3)]

runs31 = 5
runs32 = 15

pi3,mu3,sigma3 = EM(temp,Z3,runs31,runs32)

K4 = 4

temp = np.asarray(Dev_data2[3])

Z4 = temp[np.random.choice(range(temp.shape[0]),replace=False,size=K4)]

runs41 = 5
runs42 = 15

pi4,mu4,sigma4 = EM(temp,Z4,runs41,runs42)

K5 = 4

temp = np.asarray(Dev_data2[4])

Z5 = temp[np.random.choice(range(temp.shape[0]),replace=False,size=K5)]

runs51 = 5
runs52 = 15

pi5,mu5,sigma5 = EM(temp,Z5,runs51,runs52)

pi = [pi1,pi2,pi3,pi4,pi5]
mu = [mu1,mu2,mu3,mu4,mu5]
sigma = [sigma1,sigma2,sigma3,sigma4,sigma5]

N = len(Dev_data1)
C = 5
S = np.zeros((N,C))
  
for n in range(N):
  for c in range(C):
    for v in Dev_data1[n]:
      prob = Gaussian_mixture(v,pi[c],mu[c],sigma[c])
      if prob>0:
        S[n,c]+=math.log10(prob)

min = np.amin(S)
max = np.amax(S)

TPR = []
FPR = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S[i,j] >= threshold:
        if groundtruth_dev(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR.append(TP/(TP+FN))  # True positive rate
  FPR.append(FP/(FP+TN))  # False positive rate

# # plotting
# plt.title("ROC curve")
# plt.xlabel("FPR")
# plt.ylabel("TPR")
# plt.plot(FPR, TPR, color ="green")
# plt.show()

FNR = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S[i,j] >= threshold:
        if groundtruth_dev(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev(i) == j+1:
          FN+=1 
        else:
          TN+=1
  FNR.append(FN/(TP+FN))  # False negative rate

# # plotting
# plt.title("DET curve")
# plt.xlabel("False Alarm Rate")
# plt.ylabel("Missed Detection Rate")
# plt.plot(FPR, FNR, color ="red")
# plt.show()

# true_class = 1
# y_true = np.zeros(N)
# y_scores = np.zeros(N)

# for i in range(N):
#   if groundtruth_dev(i) == true_class:
#     y_true[i] = 1
#   y_scores[i] = S[i,true_class-1]

# # print(y_scores)
# fpr,fnr,thresholds = det_curve(y_true,y_scores)

# # plotting
# plt.title("DET curve")
# plt.xlabel("False Alarm Rate")
# plt.ylabel("Missed Detection Rate")
# plt.plot(fpr,fnr,color ="red")
# plt.show()

sigma_diag = []
  
for i in range(C):
  cov1 = []
  for cov in sigma[i]:
    size = len(cov)
    temp = cov
    for i in range(size):
      for j in range(size):
        if i!=j:
          temp[i][j] = 0
    cov1.append(temp)
  sigma_diag.append(cov1)

S_diag = np.zeros((N,C)) 

for n in range(N):
  for c in range(C):
    for v in Dev_data1[n]:
      prob=Gaussian_mixture(v,pi[c],mu[c],sigma_diag[c])
      if prob>0:
        S_diag[n,c]+=math.log10(prob)

min = np.amin(S_diag)
max = np.amax(S_diag)

TPR_diag = []
FPR_diag = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S_diag[i,j] >= threshold:
        if groundtruth_dev(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR_diag.append(TP/(TP+FN))  # True positive rate
  FPR_diag.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR_diag,TPR_diag,color='red',label='Diagonal covariance')
plt.plot(FPR,TPR,color='blue',label='Non-diagonal covariance')
  
# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

# plotting
# plt.title("ROC curve")
# plt.xlabel("False Positive Rate")
# plt.ylabel("True Positive Rate")
# plt.plot(FPR_diag, TPR_diag, color ="green")
# plt.show()

FPR_diag = []
FNR_diag = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S_diag[i,j] >= threshold:
        if groundtruth_dev(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev(i) == j+1:
          FN+=1 
        else:
          TN+=1
  FPR_diag.append(FP/(TN+FP))  # False positive rate
  FNR_diag.append(FN/(TP+FN))  # False negative rate

plt.plot(FPR_diag,FNR_diag,color='pink',label='Diagonal covariance')
plt.plot(FPR,FNR,color='green',label='Non-diagonal covariance')
  
# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

# plotting
# plt.title("DET curve")
# plt.xlabel("False Alarm Rate")
# plt.ylabel("Missed Detection Rate")
# plt.plot(FPR, FNR, color ="red")
# plt.show()

"""**Bonus : UBM-GMM**

**Synthetic Data**
"""

K = 3
runs1 = 5
runs2 = 8

X = [np.append(x_train,x_train_classwise[0],axis=0),np.append(x_train,x_train_classwise[1],axis=0)]

Z1 = X[0][np.random.choice(range(X[0].shape[0]),replace=False,size=K)]

Z2 = X[1][np.random.choice(range(X[1].shape[0]),replace=False,size=K)]

pi1,mu1,sigma1 = EM(X[0],Z1,runs1,runs2)

pi2,mu2,sigma2 = EM(X[1],Z2,runs1,runs2)

pi = [pi1,pi2]
mu = [mu1,mu2]
sigma = [sigma1,sigma2]

X = np.linspace(-3,3,num=2000)
Y = np.linspace(-3,3,num=2000)
X, Y = np.meshgrid(X, Y)
pos = np.empty(X.shape + (2,))
pos[:, :, 0] = X
pos[:, :, 1] = Y
Z = []
for i in range(2):
  for j in range(len(mu[0])):
    Z = pi[i][j]*Multivariate_Gaussian1(pos,mu[i][j],sigma[i][j])
    plt.contour(X,Y,Z,levels=[0.037,0.075,0.08,0.1,0.15,0.2])

plt.scatter(x1_dev,x2_dev)

def concat(mu):
  res=[]
  for temp in mu:
    res.append(mu)
  return np.asarray(res).flatten()

mu = [concat(mu1),concat(mu2)]

sample_size = 30
C = 2
S = np.zeros((sample_size,C))

sample = np.random.choice(np.arange(0,1000), size=sample_size, replace=False)

x_dev_sample = x_dev[sample]

for n in range(sample_size):
  for c in range(C):
    temp = np.append(x_dev,np.reshape(x_dev_sample[n],(1,2)),axis=0)
    Z = temp[np.random.choice(range(temp.shape[0]),replace=False,size=K)]
    pi_test,mu_test,sigma_test = EM(temp,Z,runs1,runs2)
    S[n,c] = np.dot(mu[c],concat(mu_test))/(np.linalg.norm(mu[c])*np.linalg.norm(concat(mu_test)))

def groundtruth_dev_sample(i):
  if sample[i] < 500:
    return 1
  else:
    return 2

min = np.amin(S)
max = np.amax(S)

TPR = []
FPR = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(sample_size): 
    for j in range(C):
      if S[i,j] >= threshold:
        if groundtruth_dev_sample(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_sample(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR.append(TP/(TP+FN))  # True positive rate
  FPR.append(FP/(FP+TN))  # False positive rate

# print(FPR)
# FPR1,TPR1 = sort_arrs(FPR,TPR)
# print(FPR1.shape)

# print("wd")
# print(FPR[::-1])
# cubic_interploation_model = interp1d(FPR1,TPR1,kind="cubic")

# Plotting the Graph
# X = np.linspace(FPR1.min(),FPR1.max(),500)
# Y = cubic_interploation_model(X)
 
plt.plot(FPR,TPR,color ="red")
plt.title("ROC curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()

FNR = []

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(sample_size): 
    for j in range(C):
      if S[i,j] >= threshold:
        if groundtruth_dev_sample(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_sample(i) == j+1:
          FN+=1 
        else:
          TN+=1
  FNR.append(FN/(TP+FN))  # False negative rate

# plotting
plt.title("DET curve")
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.plot(FPR, FNR, color ="green")
plt.show()

"""**Image dataset**"""

K = 5
runs1 = 5
runs2 = 8

Train = []

for a in Train_data1:
  for b in a:
    Train.append(b)

X = [np.append(Train,Train_data2[0],axis=0),np.append(Train,Train_data2[1],axis=0),np.append(Train,Train_data2[2],axis=0),np.append(Train,Train_data2[3],axis=0),np.append(Train,Train_data2[4],axis=0)]

Z1 = X[0][np.random.choice(range(X[0].shape[0]),replace=False,size=K)]

Z2 = X[1][np.random.choice(range(X[1].shape[0]),replace=False,size=K)]

Z3 = X[2][np.random.choice(range(X[2].shape[0]),replace=False,size=K)]

Z4 = X[3][np.random.choice(range(X[3].shape[0]),replace=False,size=K)]

Z5 = X[4][np.random.choice(range(X[4].shape[0]),replace=False,size=K)]

pi1,mu1,sigma1 = EM(X[0],Z1,runs1,runs2)

pi2,mu2,sigma2 = EM(X[1],Z2,runs1,runs2)

pi3,mu3,sigma3 = EM(X[2],Z3,runs1,runs2)

pi4,mu4,sigma4 = EM(X[3],Z4,runs1,runs2)

pi5,mu5,sigma5 = EM(X[4],Z5,runs1,runs2)

mu = [concat(mu1),concat(mu2),concat(mu3),concat(mu4),concat(mu5)]

sample_size = 30
C = 5
S1 = np.zeros((sample_size,C))

sample1 = np.random.choice(np.arange(0,len(Train)),size=sample_size,replace=False)

Train_sample = np.asarray(Train)[sample1]

# [0,72]
# [73,138]
# [53,190]
# [191,274]
# [275,356]
def groundtruth_dev_img_ubm(i):
  if i<=(72*36):
    return 1
  elif i<=(138*36):
    return 2
  elif i<=(190*36):
    return 3
  elif i<=(274*36):
    return 4
  else:
    return 5

for n in range(sample_size):
  for c in range(C):
    temp = np.append(Train,[Train[n]],axis=0)
    Z = temp[np.random.choice(range(temp.shape[0]),replace=False,size=K)]
    pi_test,mu_test,sigma_test = EM(temp,Z,runs1,runs2)
    S1[n,c] = np.dot(mu[c],concat(mu_test))/(np.linalg.norm(mu[c])*np.linalg.norm(concat(mu_test)))

min = np.amin(S1)
max = np.amax(S1)

TPR1 = []
FPR1 = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(sample_size): 
    for j in range(C):
      if S1[i,j] >= threshold:
        if groundtruth_dev_img_ubm(sample1[i]) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_img_ubm(sample[i]) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR1.append(TP/(TP+FN))  # True positive rate
  FPR1.append(FP/(FP+TN))  # False positive rate

# plt.plot(FPR_diag,TPR_diag,color='red',label='Diagonal covariance')
plt.plot(FPR1,TPR1,color='red')
  
# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

# plotting
# plt.title("ROC curve")
# plt.xlabel("False Positive Rate")
# plt.ylabel("True Positive Rate")
# plt.plot(FPR_diag, TPR_diag, color ="green")
# plt.show()