# -*- coding: utf-8 -*-
"""Assignment3_Part2_DTW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POh4EDE8e41UM6gRRdAbKkIUVQi4ttJ3
"""

import numpy as np
import os
import math
import random
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve
from sklearn.metrics import det_curve
from sklearn.metrics import confusion_matrix

from google.colab import drive
drive.mount('/content/drive')

"""Loading all Data"""

## Reading file into a numpy array

Train_data = []
Dev_data = []

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/3/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/3/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/3/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/3/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
      
Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/4/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/4/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/4/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/4/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/5/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/5/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/5/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/5/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/7/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/7/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/7/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/7/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/o/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/o/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/o/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/o/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))

Train_data.append(X)

Train_data_digits = []

X1=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X1.append(K)

Train_data_digits.append(X1)

X2=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X2.append(K)

Train_data_digits.append(X2)

X3=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X3.append(K)

Train_data_digits.append(X3)

X4=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X4.append(K)

Train_data_digits.append(X4)

X5=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X5.append(K)

Train_data_digits.append(X5)

Dev1=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev1.append(K)

Dev2=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev2.append(K)

Dev3=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev3.append(K)

Dev4=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev4.append(K)

Dev5=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev5.append(K)

Dev_data_digits = [Dev1,Dev2,Dev3,Dev4,Dev5]

Train_data1=[]
for clas in Train_data:
  for v in clas:
    Train_data1.append(v)

Train_datadigits=[]
for clas in Train_data_digits:
  for v in clas:
    Train_datadigits.append(v)

Dev_data1=[]
for clas in Dev_data:
  for v in clas:
    Dev_data1.append(v)

Dev_data_digits1=[]
for clas in Dev_data_digits:
  for v in clas:
    Dev_data_digits1.append(v)

def min_of_three(x,y,z):
  if x < y:
    if x < z:
      return x
    else:
      return z
  else:
    if y < z:
      return y
    else:
      return z

# Computes the DTW distance between X and Y
def DTW(X,Y):
  if len(X)<len(Y):
    return DTW(Y,X)
  M = len(X)
  N = len(Y)
  dtw = np.full((M+1,N+1),np.inf)
  dtw[0,0] = 0
  for i in range(1,M+1):    
    for j in range(1,N+1):  
      # print("sd")
      dtw[i,j] = min_of_three(dtw[i-1,j],dtw[i,j-1],dtw[i-1,j-1])+np.linalg.norm(X[i-1]-Y[j-1])
      # print("ed")
  return dtw[M,N]

def comp(x):
  return x[0]

"""Handwritten Characters"""

# Top K
def DTW_classifier(X,K):
  distances = []
  for clas in range(len(Train_data_digits)):
    # samples.append(random.sample(Train_data[clas],size))
  # distances = []
      for example in Train_data_digits[clas]:
        distances.append([DTW(X,example),clas])
    # for clas in range(len(samples)):
    #   for example in samples[clas]:
    #     distances.append([DTW(X,example),clas])
  distances.sort(key=comp)
  ans = -1
  for clas in range(len(Train_data_digits)):
    cnt = 0
    for i in range(K):
      if distances[i][1] == clas:
        cnt+=1
    if cnt > ans:
      ans = clas
    elif cnt == ans:
      if random.randint(0,1) == 1:
        ans = clas
  return distances[:K],ans

DTW_classifier(Dev_data_digits1[0][0],10)

N = len(Dev_data_digits1)
C = 5

N

K = 10

S = np.zeros((N,C))

n = 0
for clas in range(C):
  for v in Dev_data_digits[clas]:
    dist,ans = DTW_classifier(v,K)
    cnt = np.zeros(C)
    for c in range(C):
      for d in dist:
        if d[1] == c:
          cnt[c] += 1
    for c in range(C):
      S[n,c] = cnt[c]/K      
    n+=1

S

groundtruth_dev = [1]*20 + [2]*20 + [3]*20 + [4]*20 + [5]*20

min = np.min(S)
max = np.max(S)

TPR = []
FPR = []

thresholds = np.linspace(0,1,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S[i,j] >= threshold:
        if groundtruth_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR.append(TP/(TP+FN))  # True positive rate
  FPR.append(FP/(FP+TN))  # False positive rate

# plotting
plt.title("ROC curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.plot(FPR, TPR, color ="green")
plt.show()

FNR = []

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S[i,j] >= threshold:
        if groundtruth_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  FNR.append(FN/(TP+FN))

# plotting
plt.title("DET curve")
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.plot(FPR, FNR, color ="red")
plt.show()

import seaborn as sns
def conf_matrix(tc,pc):
  n = len(np.unique(tc))
  Con_Matrix1 = np.zeros((n,n))
  for i in range(len(tc)):
    Con_Matrix1[int(tc[i])-1][int(pc[i])-1]+=1
  
  c = []
  r = []
  s=0
  for i in range(len(Con_Matrix1)):
    c.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1[i])*100)
    r.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1.T[i])*100)
    s+=Con_Matrix1[i][i]

  r.append(s/np.sum(Con_Matrix1)*100)
    
  Con_Matrix1 = np.c_[Con_Matrix1,c]
  Con_Matrix1 = np.vstack((Con_Matrix1,r))

  classes = []
  for i in range(n):
    classes.append("class "+str(i+1))
  font = {'family': 'serif',
          'color':  'red',
          'weight': 'bold',
          'size': 16,
          }
  ax = sns.heatmap(Con_Matrix1, annot=True, fmt="g")
  ax.xaxis.set_ticklabels(classes)
  plt.title('Confusion Matrix',fontdict = font)
  ax.set_xlabel('Predicted',fontdict = font)
  ax.set_ylabel('True',fontdict = font)
  ax.yaxis.set_ticklabels(classes)
  plt.show()

y_pred = np.argmax(S, axis = 1)+1
print(y_pred)

conf_matrix(groundtruth_dev,y_pred)

"""Isolated Digits"""

def DTW_classifier(X,K):
  distances = []
  for clas in range(len(Train_data)):
    # samples.append(random.sample(Train_data[clas],size))
  # distances = []
      for example in Train_data[clas]:
        distances.append([DTW(X,example),clas])
    # for clas in range(len(samples)):
    #   for example in samples[clas]:
    #     distances.append([DTW(X,example),clas])
  distances.sort(key=comp)
  ans = -1
  for clas in range(len(Train_data)):
    cnt = 0
    for i in range(K):
      if distances[i][1] == clas:
        cnt+=1
    if cnt > ans:
      ans = clas
    elif cnt == ans:
      if random.randint(0,1) == 1:
        ans = clas
  return distances[:K],ans

DTW_classifier(Dev_data1[0][0],10)

N = len(Dev_data1)
C = 5

S1 = np.zeros((N,C))

n = 0
for clas in range(C):
  for v in Dev_data[clas]:
    dist,ans = DTW_classifier(v,K)
    cnt = np.zeros(C)
    for c in range(C):
      for d in dist:
        if d[1] == c:
          cnt[c] += 1
    for c in range(C):
      S1[n,c] = cnt[c]/K      
    n+=1

S1

groundtruth_dev1 = [1]*12 + [2]*12 + [3]*12 + [4]*12 + [5]*12

min = np.min(S1)
max = np.max(S1)

TPR = []
FPR = []

thresholds = np.linspace(0,1,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S1[i,j] >= threshold:
        if groundtruth_dev1[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev1[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR.append(TP/(TP+FN))  # True positive rate
  FPR.append(FP/(FP+TN))  # False positive rate

# plotting
plt.title("ROC curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.plot(FPR, TPR, color ="green")
plt.show()

FNR = []

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S1[i,j] >= threshold:
        if groundtruth_dev1[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev1[i] == j+1:
          FN+=1 
        else:
          TN+=1
  FNR.append(FN/(TP+FN))

# plotting
plt.title("DET curve")
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.plot(FPR, FNR, color ="red")
plt.show()

y_pred1 = np.argmax(S1, axis = 1)+1
print(y_pred1)

conf_matrix(groundtruth_dev1,y_pred1)