# -*- coding: utf-8 -*-
"""Assignment HMM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DL282RfSyIr_AhtUw6m2yF_xlU6GTkVr
"""

import numpy as np
import os
import math
import random
import matplotlib.pyplot as plt
import stat

from google.colab import drive
drive.mount('/content/drive')

"""Kmeans"""

def K_means(X,Z,runs): 
  N = len(X) 
  K = len(Z)
  d = len(X[0])
  r = np.zeros(N) 
  for run in range(runs):
    for n in range(N):
      dist = np.inf
      cluster = -1
      for k in range(K):
        if np.linalg.norm(X[n]-Z[k]) < dist:
          dist = np.linalg.norm(X[n]-Z[k])
          cluster = k
        elif np.linalg.norm(X[n]-Z[k]) == dist:
          if random.randint(0,1) == 1:
            cluster = k
      r[n] = cluster
    for k in range(K):
      sum = np.zeros(d)
      cnt = 0
      for n in range(N):
        if r[n]==k:
          sum += X[n]
          cnt += 1  
      Z[k] = sum/cnt 
  return Z,r

## Reading file into a numpy array

Training_data = []

X1=[]

os.chdir('/content/drive/MyDrive/Isolated_Digits/3/train')

# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/3/train'}/{file}" 
    X1.append(np.loadtxt(file_path, skiprows=1))
      
Training_data.append(X1)

X2=[]
Training_data_4 = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/4/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/4/train'}/{file}" 
    X2.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X2)

X3=[]
Training_data_5 = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/5/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/5/train'}/{file}" 
    X3.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X3)

X4=[]
Training_data_7 = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/7/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/7/train'}/{file}" 
    X4.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X4)
Training_data_o = []
X5=[]

os.chdir('/content/drive/MyDrive/Isolated_Digits/o/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/o/train'}/{file}" 
    X5.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X5)

x_3 = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/3/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/3/dev'}/{file}" 
    x_3.append(np.loadtxt(file_path, skiprows=1))

x_4=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/4/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/4/dev'}/{file}" 
    x_4.append(np.loadtxt(file_path, skiprows=1))

x_5 = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/5/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/5/dev'}/{file}" 
    x_5.append(np.loadtxt(file_path, skiprows=1))

x_7=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/7/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/7/dev'}/{file}" 
    x_7.append(np.loadtxt(file_path, skiprows=1))

x_o = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/o/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/o/dev'}/{file}" 
    x_o.append(np.loadtxt(file_path, skiprows=1))

"""Preprocessing"""

L = []
for M in Training_data:
  for x in M:
    for v in x:
      L.append(v)
L = np.asarray(L)

L.shape

"""K = 20"""

K1 = 10
L = np.reshape(L,(19253,38))
Z1 = L[np.random.choice(range(L.shape[0]),replace=False,size=K1)]
A,B = K_means(L,Z1,30)

os.chdir('/content')

"""Unzip HMM code"""

!unzip /content/drive/MyDrive/HMM-Code.zip

os.chdir('/content/HMM-Code')

!make clean

!make all

!chmod +rwx /content/HMM-Code/test_hmm

"""CODEBOOK"""

X_3 = []
for i in X1:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_3.append(C)

file = open("3T.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_3:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_4 = []
for i in X2:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_4.append(C)

file = open("4T.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_4:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_5 = []
for i in X3:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_5.append(C)

file = open("5T.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_5:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_7 = []
for i in X4:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_7.append(C)

file = open("7T.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_7:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_o = []
for i in X5:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_o.append(C)

file = open("oT.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_o:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

"""HMM Training"""

!/content/HMM-Code/train_hmm 3T.txt 1234 15 10 .01

!/content/HMM-Code/train_hmm 4T.txt 1234 15 10 .01

!/content/HMM-Code/train_hmm 5T.txt 42 15 10 .01

!/content/HMM-Code/train_hmm 7T.txt 42 15 10 .01

!/content/HMM-Code/train_hmm oT.txt 42 15 10 .01

!chmod +rwx /content/HMM-Code/3T.txt.hmm
!chmod +rwx /content/HMM-Code/4T.txt.hmm
!chmod +rwx /content/HMM-Code/5T.txt.hmm
!chmod +rwx /content/HMM-Code/7T.txt.hmm
!chmod +rwx /content/HMM-Code/oT.txt.hmm

"""Dev Data"""

X_3 = []
for i in x_3:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_3.append(C)

X_4 = []
for i in x_4:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_4.append(C)

X_5 = []
for i in x_5:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_5.append(C)

X_7 = []
for i in x_7:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_7.append(C)

X_o = []
for i in x_o:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_o.append(C)

file = open("3D.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_3:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("4D.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_4:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("5D.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_5:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("7D.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_7:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("oD.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_o:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

"""Testing

3
"""

three = []
!/content/HMM-Code/test_hmm 3D.txt /content/HMM-Code/3T.txt.hmm .01
three.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 4D.txt /content/HMM-Code/3T.txt.hmm .01
three.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 5D.txt /content/HMM-Code/3T.txt.hmm .01
three.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 7D.txt /content/HMM-Code/3T.txt.hmm .01
three.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm oD.txt /content/HMM-Code/3T.txt.hmm .01
three.append(np.loadtxt('/content/HMM-Code/alphaout'))
three = np.asarray(three)
three = np.reshape(three,(60,1))

"""4"""

four = []
!/content/HMM-Code/test_hmm 3D.txt /content/HMM-Code/4T.txt.hmm .01
four.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 4D.txt /content/HMM-Code/4T.txt.hmm .01
four.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 5D.txt /content/HMM-Code/4T.txt.hmm .01
four.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 7D.txt /content/HMM-Code/4T.txt.hmm .01
four.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm oD.txt /content/HMM-Code/4T.txt.hmm .01
four.append(np.loadtxt('/content/HMM-Code/alphaout'))
four = np.asarray(four)
four = np.reshape(four,(60,1))

"""Five"""

Five = []
!/content/HMM-Code/test_hmm 3D.txt /content/HMM-Code/5T.txt.hmm .01
Five.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 4D.txt /content/HMM-Code/5T.txt.hmm .01
Five.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 5D.txt /content/HMM-Code/5T.txt.hmm .01
Five.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 7D.txt /content/HMM-Code/5T.txt.hmm .01
Five.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm oD.txt /content/HMM-Code/5T.txt.hmm .01
Five.append(np.loadtxt('/content/HMM-Code/alphaout'))
Five = np.asarray(Five)
Five = np.reshape(Five,(60,1))

"""Seven"""

seven = []
!/content/HMM-Code/test_hmm 3D.txt /content/HMM-Code/7T.txt.hmm .01
seven.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 4D.txt /content/HMM-Code/7T.txt.hmm .01
seven.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 5D.txt /content/HMM-Code/7T.txt.hmm .01
seven.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 7D.txt /content/HMM-Code/7T.txt.hmm .01
seven.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm oD.txt /content/HMM-Code/7T.txt.hmm .01
seven.append(np.loadtxt('/content/HMM-Code/alphaout'))
seven = np.asarray(seven)
seven = np.reshape(seven,(60,1))

"""O"""

O = []
!/content/HMM-Code/test_hmm 3D.txt /content/HMM-Code/oT.txt.hmm .01
O.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 4D.txt /content/HMM-Code/oT.txt.hmm .01
O.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 5D.txt /content/HMM-Code/oT.txt.hmm .01
O.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm 7D.txt /content/HMM-Code/oT.txt.hmm .01
O.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm oD.txt /content/HMM-Code/oT.txt.hmm .01
O.append(np.loadtxt('/content/HMM-Code/alphaout'))
O = np.asarray(O)
O = np.reshape(O,(60,1))

S = []
S.append(three)
S.append(four)
S.append(Five)
S.append(seven)
S.append(O)

S = np.asarray(S)
S.shape

S = np.reshape(S,(5,60))

s = S.T

li = [1]*12 + [2]*12 + [3]*12 + [4]*12 + [5]*12

"""ROC"""

M = 60
N = 5 

min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

"""DET"""

min = np.amin(s)
max = np.amax(s)

FPR = []
FNR = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j+1:
          FN+=1 
        else:
          TN+=1
  FPR.append(FP/(TN+FP))  # True positive rate
  FNR.append(FN/(TP+FN))  # False positive rate

# plotting
plt.title("DET curve")
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.plot(FPR, FNR, color ="red")
plt.show()

"""Confusion Matrix"""

import seaborn as sns
def conf_matrix(tc,pc):
  n = len(np.unique(tc))
  Con_Matrix1 = np.zeros((n,n))
  for i in range(len(tc)):
    Con_Matrix1[int(tc[i])-1][int(pc[i])-1]+=1
  
  c = []
  r = []
  s=0
  for i in range(len(Con_Matrix1)):
    c.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1[i])*100)
    r.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1.T[i])*100)
    s+=Con_Matrix1[i][i]

  r.append(s/np.sum(Con_Matrix1)*100)
    
  Con_Matrix1 = np.c_[Con_Matrix1,c]
  Con_Matrix1 = np.vstack((Con_Matrix1,r))

  classes = []
  for i in range(n):
    classes.append("class "+str(i+1))
  font = {'family': 'serif',
          'color':  'red',
          'weight': 'bold',
          'size': 16,
          }
  ax = sns.heatmap(Con_Matrix1, annot=True, fmt="g")
  ax.xaxis.set_ticklabels(classes)
  plt.title('Confusion Matrix',fontdict = font)
  ax.set_xlabel('Predicted',fontdict = font)
  ax.set_ylabel('True',fontdict = font)
  ax.yaxis.set_ticklabels(classes)
  plt.show()

y_pred = np.argmax(s, axis = 1)+1
print(y_pred)

conf_matrix(li,y_pred)

"""Bonus"""

x_bonus = []
os.chdir('/content/drive/MyDrive/Connected_Digits/test/team4')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith("5.mfcc"):
        file_path = f"{'/content/drive/MyDrive/Connected_Digits/test/team4'}/{file}" 
        print(file)
        x_bonus.append(np.loadtxt(file_path, skiprows=1))

x_b3 = []
for i in x_bonus:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  x_b3.append(C)

x_b3

os.chdir("/content/HMM-Code/")
file = open("4.txt", "w+")
 
# Saving the 2D array in a text file
for i in x_b3:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

"""two digits together"""

two_Per=[]
cat_names = ["3T","4T","5T","7T","oT"]
main_directory = "/content/HMM-Code/"
for i in range(5):
  for j in range(5):
    x_T=[]
    directory = os.path.join(main_directory,cat_names[i]+".txt.hmm")
    os.chdir("/content/HMM-Code/")
    x_T.append(np.loadtxt(directory, skiprows=2))

    directory = os.path.join(main_directory,cat_names[j]+".txt.hmm")
    os.chdir("/content/HMM-Code/")
    x_T.append(np.loadtxt(directory, skiprows=2))

    x_T = np.asarray(x_T)
    file_name = cat_names[i] + '_' + cat_names[j] + '.txt.hmm'
    two_Per.append(file_name)

    file = open(file_name, "w+")
    file.write('states: 30')
    file.write("\n")
    file.write('symbols: 20')
    file.write("\n")
    e = 0
    for w in x_T:
      for r in w: 
        e = e+1
        for g in range(len(r)):
          # print(i[j])
          if j!=len(r)-1:
            file.write(str((r[g]))+' ')
          else: 
            file.write(str(r[g]))
        file.write("\n")
        if e%2==0:
          file.write("\n")
    file.close()

for i in two_Per:
  !chmod +rwx /content/HMM-Code/{i}

C_B = []
for i in two_Per:
  !/content/HMM-Code/test_hmm 4.txt /content/HMM-Code/{i} .01
  C_B.append(np.loadtxt('/content/HMM-Code/alphaout'))
C_B = np.asarray(C_B)

C_B

idx = np.argmax(C_B)
two_Per[idx]

C_B[idx] = -np.inf

"""Three connected digits"""

three_Per=[]
cat_names = ["3T","4T","5T","7T","oT"]
main_directory = "/content/HMM-Code/"
for f in range(5): 
  for i in range(5):
    for j in range(5):
      x_T=[]
      directory = os.path.join(main_directory,cat_names[f]+".txt.hmm")
      os.chdir("/content/HMM-Code/")
      x_T.append(np.loadtxt(directory, skiprows=2))

      directory = os.path.join(main_directory,cat_names[i]+".txt.hmm")
      os.chdir("/content/HMM-Code/")
      x_T.append(np.loadtxt(directory, skiprows=2))

      directory = os.path.join(main_directory,cat_names[j]+".txt.hmm")
      os.chdir("/content/HMM-Code/")
      x_T.append(np.loadtxt(directory, skiprows=2))

      x_T = np.asarray(x_T)
      file_name = cat_names[f] + '_' + cat_names[i] + '_' + cat_names[j] + '.txt.hmm'
      three_Per.append(file_name)

      file = open(file_name, "w+")
      file.write('states: 45')
      file.write("\n")
      file.write('symbols: 20')
      file.write("\n")
      e = 0
      for w in x_T:
        for r in w: 
          e = e+1
          for g in range(len(r)):
            # print(i[j])
            if j!=len(r)-1:
              file.write(str((r[g]))+' ')
            else: 
              file.write(str(r[g]))
          file.write("\n")
          if e%2==0:
            file.write("\n")
      file.close()

for i in three_Per:
  !chmod +rwx /content/HMM-Code/{i}

C_B1 = []
for i in three_Per:
  !/content/HMM-Code/test_hmm 4.txt /content/HMM-Code/{i} .01
  C_B1.append(np.loadtxt('/content/HMM-Code/alphaout'))
C_B1 = np.asarray(C_B1)

C_B1

idx1 = np.argmax(C_B1)
three_Per[idx1]

C_B1[idx1] = -np.inf

"""Handwritten

"""

os.chdir('/content/drive/MyDrive/Handwriting_Data')

"""Extracting slope as another feature"""

Training_data1 = []

X1=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X1.append(K)

# from numpy import diff
# x = K[:,0]
# y = K[:,1]
# dydx = diff(y)/diff(x)
# K = np.Concatenate(K,dydx,axis=1)


Training_data1.append(X1)

X2=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X2.append(K)

Training_data1.append(X2)

X3=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X3.append(K)

Training_data1.append(X3)

X4=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X4.append(K)

Training_data1.append(X4)

X5=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X5.append(K)

Training_data1.append(X5)

"""Preprocessing"""

L1 = []
for M in Training_data1:
  for x in M:
    for v in x:
      L1.append(v)

L1 = np.asarray(L1)
L1.shape

os.chdir('/content/HMM-Code')

"""K =20"""

K1 = 20
L1 = np.reshape(L1,(26859,3))
Z1 = L1[np.random.choice(range(L1.shape[0]),replace=False,size=K1)]
A,B = K_means(L1,Z1,30)

X_a = []
for i in X1:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_a.append(C)

file = open("aT.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_a:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_ai = []
for i in X2:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_ai.append(C)

file = open("aiT.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_ai:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_bA = []
for i in X3:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_bA.append(C)

file = open("bAT.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_bA:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_chA = []
for i in X4:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_chA.append(C)

X_chA

file = open("chAT.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_chA:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

X_dA = []
for i in X5:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_dA.append(C)

file = open("dAT.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_dA:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

"""HMM Training

Sample = 10
"""

!/content/HMM-Code/train_hmm aT.txt 1234 10 20 .01

!/content/HMM-Code/train_hmm aiT.txt 1234 10 20 .01

!/content/HMM-Code/train_hmm bAT.txt 42 10 20 .01

!/content/HMM-Code/train_hmm chAT.txt 1234 10 20 .01

!/content/HMM-Code/train_hmm dAT.txt 1234 10 20 .01

"""Dev Data"""

X21=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X21.append(K)

X_a = []
for i in X21:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_a.append(C)

X31=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X31.append(K)

X_ai=[]

for i in X31:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_ai.append(C)

X41=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X41.append(K)

X_bA=[]
for i in X41:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_bA.append(C)

X51=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X51.append(K)

X_chA=[]
for i in X51:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_chA.append(C)

X61=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X61.append(K)

X_dA=[]
for i in X61:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  X_dA.append(C)

os.chdir('/content/HMM-Code')

file = open("aD.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_a:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("aiD.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_ai:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("bAD.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_bA:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("chAD.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_chA:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

file = open("dAD.txt", "w+")
 
# Saving the 2D array in a text file
for i in X_dA:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

!chmod +rwx /content/HMM-Code/aT.txt.hmm
!chmod +rwx /content/HMM-Code/aiT.txt.hmm
!chmod +rwx /content/HMM-Code/bAT.txt.hmm
!chmod +rwx /content/HMM-Code/chAT.txt.hmm
!chmod +rwx /content/HMM-Code/dAT.txt.hmm

"""Testing

a
"""

a = []
!/content/HMM-Code/test_hmm aD.txt /content/HMM-Code/aT.txt.hmm .01
a.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm aiD.txt /content/HMM-Code/aT.txt.hmm .01
a.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm bAD.txt /content/HMM-Code/aT.txt.hmm .01
a.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm chAD.txt /content/HMM-Code/aT.txt.hmm .01
a.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm dAD.txt /content/HMM-Code/aT.txt.hmm .01
a.append(np.loadtxt('/content/HMM-Code/alphaout'))

a = np.asarray(a)
a = np.reshape(a,(1,100))

"""ai"""

ai = []
!/content/HMM-Code/test_hmm aD.txt /content/HMM-Code/aiT.txt.hmm .01
ai.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm aiD.txt /content/HMM-Code/aiT.txt.hmm .01
ai.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm bAD.txt /content/HMM-Code/aiT.txt.hmm .01
ai.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm chAD.txt /content/HMM-Code/aiT.txt.hmm .01
ai.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm dAD.txt /content/HMM-Code/aiT.txt.hmm .01
ai.append(np.loadtxt('/content/HMM-Code/alphaout'))

ai = np.asarray(ai)
ai = np.reshape(ai,(1,100))

"""bA"""

bA = []
!/content/HMM-Code/test_hmm aD.txt /content/HMM-Code/bAT.txt.hmm .01
bA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm aiD.txt /content/HMM-Code/bAT.txt.hmm .01
bA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm bAD.txt /content/HMM-Code/bAT.txt.hmm .01
bA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm chAD.txt /content/HMM-Code/bAT.txt.hmm .01
bA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm dAD.txt /content/HMM-Code/bAT.txt.hmm .01
bA.append(np.loadtxt('/content/HMM-Code/alphaout'))

bA = np.asarray(bA)
bA = np.reshape(bA,(1,100))

"""chA"""

chA = []
!/content/HMM-Code/test_hmm aD.txt /content/HMM-Code/chAT.txt.hmm .01
chA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm aiD.txt /content/HMM-Code/chAT.txt.hmm .01
chA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm bAD.txt /content/HMM-Code/chAT.txt.hmm .01
chA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm chAD.txt /content/HMM-Code/chAT.txt.hmm .01
chA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm dAD.txt /content/HMM-Code/chAT.txt.hmm .01
chA.append(np.loadtxt('/content/HMM-Code/alphaout'))

chA = np.asarray(chA)
chA = np.reshape(chA,(1,100))

"""dA"""

dA = []
!/content/HMM-Code/test_hmm aD.txt /content/HMM-Code/dAT.txt.hmm .01
dA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm aiD.txt /content/HMM-Code/dAT.txt.hmm .01
dA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm bAD.txt /content/HMM-Code/dAT.txt.hmm .01
dA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm chAD.txt /content/HMM-Code/dAT.txt.hmm .01
dA.append(np.loadtxt('/content/HMM-Code/alphaout'))
!/content/HMM-Code/test_hmm dAD.txt /content/HMM-Code/dAT.txt.hmm .01
dA.append(np.loadtxt('/content/HMM-Code/alphaout'))

dA = np.asarray(dA)
dA = np.reshape(dA,(1,100))

li = [1]*20 +[2]*20 + [3]*20+ [4]*20 + [5]*20

S = []
S.append(np.asarray(a))
S.append(np.asarray(ai))
S.append(np.asarray(bA))
S.append(np.asarray(chA))
S.append(np.asarray(dA))
S = np.asarray(S)

S.shape

S = np.reshape(S,(5,100))

s = S.T

"""ROC"""

M = 100
N = 5 

min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

"""DET"""

min = np.amin(s)
max = np.amax(s)

FPR = []
FNR = []

thresholds = np.linspace(min,max,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j+1:
          FN+=1 
        else:
          TN+=1
  FPR.append(FP/(TN+FP))  # True positive rate
  FNR.append(FN/(TP+FN))  # False positive rate

# plotting
plt.title("DET curve")
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.plot(FPR, FNR, color ="red")
plt.show()

y_pred = np.argmax(s, axis = 1)+1
y_pred

"""Confusion Matrix"""

conf_matrix(li,y_pred)

"""HMM Bonus

Connected Handwritten Characters
"""

x_bonus1=[]
M = np.loadtxt('/content/drive/MyDrive/Connected_Handwritten_Characters/test/team4/5.txt')
K = []
for i in range(1,len(M)-4,2):
  K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
for i in range(len(M)-3,len(M)-1):
  K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
K = np.asarray(K)
x_bonus1.append(K)

x_b1 = []
for i in x_bonus1:
  C = []
  for j in i:
    dist = np.inf
    cluster = -1
          # print("hbh")
    for k in range(K1):
      if np.linalg.norm(j-A[k]) < dist:
        dist = np.linalg.norm(j-A[k])
        cluster = k
      elif np.linalg.norm(j-A[k]) == dist:
        if random.randint(0,1) == 1:
          cluster = k
    C.append(cluster)
  C = np.asarray(C)
  x_b1.append(C)

os.chdir("/content/HMM-Code/")
file = open("abc.txt", "w+")
 
# Saving the 2D array in a text file
for i in x_b1:
  for j in range(len(i)):
    # if j!=0 and j!=len(i)-1:
    if j!=len(i)-1:
      file.write(str(int(i[j]))+' ')
    else: 
      file.write(str(int(i[j])))
  file.write("\n")
file.close()

two_Per1=[]
cat_names = ["aT","aiT","bAT","chAT","dAT"]
main_directory = "/content/HMM-Code/"
for i in range(5):
  for j in range(5):
    x_T=[]
    directory = os.path.join(main_directory,cat_names[i]+".txt.hmm")
    os.chdir("/content/HMM-Code/")
    x_T.append(np.loadtxt(directory, skiprows=2))

    directory = os.path.join(main_directory,cat_names[j]+".txt.hmm")
    os.chdir("/content/HMM-Code/")
    x_T.append(np.loadtxt(directory, skiprows=2))

    x_T = np.asarray(x_T)
    file_name = cat_names[i] + '_' + cat_names[j] + '.txt.hmm'
    two_Per1.append(file_name)

    file = open(file_name, "w+")
    file.write('states: 20')
    file.write("\n")
    file.write('symbols: 20')
    file.write("\n")
    e = 0
    for w in x_T:
      for r in w: 
        e = e+1
        for g in range(len(r)):
          # print(i[j])
          if j!=len(r)-1:
            file.write(str((r[g]))+' ')
          else: 
            file.write(str(r[g]))
        file.write("\n")
        if e%2==0:
          file.write("\n")
    file.close()

two_Per1

for i in two_Per1:
  !chmod +rwx /content/HMM-Code/{i}

C_B11 = []
for i in two_Per1:
  !/content/HMM-Code/test_hmm abc.txt /content/HMM-Code/{i} .01
  C_B11.append(np.loadtxt('/content/HMM-Code/alphaout'))
C_B11 = np.asarray(C_B11)

C_B11

idx = np.argmax(C_B11)
two_Per1[idx]

C_B11[idx] = -np.inf

"""Three connected handwritten characters"""

three_Per1=[]
cat_names = ["aT","aiT","bAT","chAT","dAT"]
main_directory = "/content/HMM-Code/"
for f in range(5): 
  for i in range(5):
    for j in range(5):
      x_T=[]
      directory = os.path.join(main_directory,cat_names[f]+".txt.hmm")
      os.chdir("/content/HMM-Code/")
      x_T.append(np.loadtxt(directory, skiprows=2))

      directory = os.path.join(main_directory,cat_names[i]+".txt.hmm")
      os.chdir("/content/HMM-Code/")
      x_T.append(np.loadtxt(directory, skiprows=2))

      directory = os.path.join(main_directory,cat_names[j]+".txt.hmm")
      os.chdir("/content/HMM-Code/")
      x_T.append(np.loadtxt(directory, skiprows=2))

      x_T = np.asarray(x_T)
      file_name = cat_names[f] + '_' + cat_names[i] + '_' + cat_names[j] + '.txt.hmm'
      three_Per1.append(file_name)

      file = open(file_name, "w+")
      file.write('states: 30')
      file.write("\n")
      file.write('symbols: 20')
      file.write("\n")
      e = 0
      for w in x_T:
        for r in w: 
          e = e+1
          for g in range(len(r)):
            # print(i[j])
            if j!=len(r)-1:
              file.write(str((r[g]))+' ')
            else: 
              file.write(str(r[g]))
          file.write("\n")
          if e%2==0:
            file.write("\n")
      file.close()

three_Per1

for i in three_Per1:
  !chmod +rwx /content/HMM-Code/{i}

C_B12 = []
for i in three_Per1:
  !/content/HMM-Code/test_hmm abc.txt /content/HMM-Code/{i} .01
  C_B12.append(np.loadtxt('/content/HMM-Code/alphaout'))
C_B12 = np.asarray(C_B12)

C_B12

idx1 = np.argmax(C_B12)
three_Per1[idx1]

C_B12[idx1] = -np.inf