# -*- coding: utf-8 -*-
"""Assignment2_Part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fQBKR26jctFPP8h_Aulzl9SbYZtSa62R
"""

import numpy as np
import math
import random
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

from google.colab import drive
drive.mount('/content/drive')

## Reading file into a numpy array
x_train,t_train = np.loadtxt("/content/drive/MyDrive/1d_team_4_train.txt", unpack=True)
x_dev,t_dev = np.loadtxt("/content/drive/MyDrive/1d_team_4_dev.txt", unpack=True)

"""**1D dataset**"""

# Least square regression for 1-D dataset

N = 200;

E_RMS_train = []
E_RMS_dev = []

model_complexity = [1,2,3,4,5,6,7,8]

for M in model_complexity:

  a = np.zeros([M,M])
  c = np.zeros(M)

  idx = random.sample(range(200), N)
  x_temp = np.zeros(N)
  t_temp = np.zeros(N)

  for i in range(N):
    x_temp[i] = x_train[idx[i]]
    t_temp[i] = t_train[idx[i]]

  for i in range(M):
    for j in range(M):
      for n in range(N):
        a[i,j] += x_temp[n]**(i+j)

  for i in range(M):
    for n in range(N):
      c[i] += t_temp[n]*(x_temp[n]**i)

  w = np.linalg.inv(a)@c

  # model
  def y1(x):
    sum = 0
    for i in range(M):
      sum += w[i]*(x**i)        
    return sum

  sum = 0

  for n in range(N):
    sum += (y1(x_train[n])-t_train[n])**2

  E_RMS_train.append((sum/N)**0.5)

  sum = 0

  for n in range(N):
    sum += (y1(x_dev[n])-t_dev[n])**2

  E_RMS_dev.append((sum/N)**0.5)

  x1 = np.linspace(0,5,100)

  # plotting
  print('complexity = ')
  print(M)
  plt.xlabel("Input features")
  plt.ylabel("Predicted outputs")
  plt.plot(x1, y1(x1), color ="red")
  plt.show()

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot([0,1,2,3,4,5,6,7], E_RMS_train, color ="blue")
plt.show()

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot([0,1,2,3,4,5,6,7], E_RMS_dev, color ="purple")
plt.show()

# Optimal M = 2,3,4

M_opt = 3

test_size = [10,50,100,120,150,200]

E_RMS_train = []
E_RMS_dev = []

for N in test_size:

  a = np.zeros([M_opt,M_opt])
  c = np.zeros(M_opt)

  idx = random.sample(range(200), N)
  x_temp = np.zeros(N)
  t_temp = np.zeros(N)

  for i in range(N):
    x_temp[i] = x_train[idx[i]]
    t_temp[i] = t_train[idx[i]]

  for i in range(M_opt):
    for j in range(M_opt):
      for n in range(N):
        a[i,j] += x_temp[n]**(i+j)

  for i in range(M_opt):
    for n in range(N):
      c[i] += t_temp[n]*(x_temp[n]**i)

  w = np.linalg.inv(a)@c

  # model
  def y1(x):
    sum = 0
    for i in range(M_opt):
      sum += w[i]*(x**i)        
    return sum

  sum = 0

  for n in range(N):
    sum += (y1(x_train[n])-t_train[n])**2

  E_RMS_train.append((sum/N)**0.5)

  sum = 0

  for n in range(N):
    sum += (y1(x_dev[n])-t_dev[n])**2

  E_RMS_dev.append((sum/N)**0.5)

  # plotting
  plt.xlabel("Input features")
  plt.ylabel("Predicted outputs")
  plt.plot(x1, y1(x1), color ="red")
  plt.show()

# plotting
plt.xlabel("Number of data points used to build the model")
plt.ylabel("Root Mean Squared Error")
plt.plot(test_size, E_RMS_train, color ="blue")
plt.show()

# plotting
plt.xlabel("Number of data points used to build the model")
plt.ylabel("Root Mean Squared Error")
plt.plot(test_size, E_RMS_dev, color ="purple")
plt.show()
## Obs : 9-16 downwards

# Ridge regression for 1-D dataset

N = 200;

E_RMS_train = []
E_RMS_dev = []

model_complexity = [1,2,3,4,5,6,7]

for M in model_complexity:

  phi = np.zeros([N,M])
  lam = math.exp(-18)

  idx = random.sample(range(200), N)
  x_temp = np.zeros(N)
  t_temp = np.zeros(N)

  for i in range(N):
    x_temp[i] = x_train[idx[i]]
    t_temp[i] = t_train[idx[i]]

  for i in range(N):
    for j in range(M):
      phi[i,j] = x_temp[i]**j

  w = np.linalg.inv(np.add(phi.T@phi,lam*np.eye(M)))@(phi.T)@(t_temp)

  # model
  def y2(x):
    sum = 0
    for i in range(M):
      sum += w[i]*(x**i)        
    return sum + (lam/2)*np.sum(w**2)

  sum = 0

  for n in range(N):
    sum += (y2(x_train[n])-t_train[n])**2

  E_RMS_train.append((sum/N)**0.5)

  sum = 0

  for n in range(N):
    sum += (y2(x_dev[n])-t_dev[n])**2

  E_RMS_dev.append((sum/N)**0.5)

  x2 = np.linspace(0,5,100)

  # plotting
  plt.xlabel("Input features")
  plt.ylabel("Predicted outputs")
  plt.plot(x2, y2(x2), color ="red")
  plt.show()

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot(model_complexity, E_RMS_train, color ="blue")
plt.show()

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot(model_complexity, E_RMS_dev, color ="purple")
plt.show()

###############

## Opt_M = 2,3,4

M_opt = 4

E_RMS_train = []
E_RMS_dev = []

lambdas = np.arange(-100,0)

for lam in lambdas:

  lam = math.exp(lam)
  phi = np.zeros([N,M_opt])

  idx = random.sample(range(200), N)
  x_temp = np.zeros(N)
  t_temp = np.zeros(N)

  for i in range(N):
    x_temp[i] = x_train[idx[i]]
    t_temp[i] = t_train[idx[i]]

  for i in range(N):
    for j in range(M_opt):
      phi[i,j] = x_temp[i]**j

  w = np.linalg.inv(np.add(phi.T@phi,lam*np.eye(M_opt)))@(phi.T)@(t_temp)

  # model
  def y2(x):
    sum = 0
    for i in range(M_opt):
      sum += w[i]*(x**i)        
    return sum + (lam/2)*np.sum(w**2)

  sum = 0

  for n in range(N):
    sum += (y2(x_train[n])-t_train[n])**2

  E_RMS_train.append((sum/N)**0.5)

  sum = 0

  for n in range(N):
    sum += (y2(x_dev[n])-t_dev[n])**2

  E_RMS_dev.append((sum/N)**0.5)

  x2 = np.linspace(0,5,100)

  # plotting
  plt.xlabel("Input features")
  plt.ylabel("Predicted outputs")
  plt.plot(x2, y2(x2), color ="red")
  plt.show()

# plotting
plt.xlabel("ln(lambda)")
plt.ylabel("Root Mean Squared Error")
plt.plot(lambdas, E_RMS_train, color ="blue")
plt.show()

# plotting
plt.xlabel("ln(lambda)")
plt.ylabel("Root Mean Squared Error")
plt.plot(lambdas, E_RMS_dev, color ="purple")
plt.show()

lam_opt = math.exp(-20)

test_size = [10,50,100,120,150,200]

for N in test_size:

  phi = np.zeros([N,M_opt])

  idx = random.sample(range(200), N)
  x_temp = np.zeros(N)
  t_temp = np.zeros(N)

  for i in range(N):
    x_temp[i] = x_train[idx[i]]
    t_temp[i] = t_train[idx[i]]

  for i in range(N):
    for j in range(M_opt):
      phi[i,j] = x_temp[i]**j

  w = np.linalg.inv(np.add(phi.T@phi,lam_opt*np.eye(M_opt)))@(phi.T)@(t_temp)

  # model
  def y2(x):
    sum = 0
    for i in range(M_opt):
      sum += w[i]*(x**i)        
    return sum + (lam_opt/2)*np.sum(w**2)

  x2 = np.linspace(0,5,100)

  # plotting
  plt.xlabel("Input features")
  plt.ylabel("Predicted outputs")
  plt.plot(x2, y2(x2), color ="red")
  plt.show()

"""**2D dataset**"""

## Reading file into a numpy array
x1_train,x2_train,t_train = np.loadtxt("/content/drive/MyDrive/2d_team_4_train.txt", unpack=True)
x1_dev,x2_dev,t_dev = np.loadtxt("/content/drive/MyDrive/2d_team_4_dev.txt", unpack=True)

N = 1000   # size of the training data
M = 5      # model complexity

# Least square regression for 2-D dataset

N = 200

E_RMS_train = []
E_RMS_dev = []

model_complexity = [1,2,3,4,5,6,7,8]

degrees = [0,1,2,3,4,5,6,7]

for M in model_complexity:
  
  phi = np.zeros([N,M])

  idx1 = random.sample(range(N), N)
  idx2 = random.sample(range(N), N)
  x1_train_rand = np.zeros(N)
  x2_train_rand = np.zeros(N)
  t_train_rand = np.zeros(N)
  x1_dev_rand = np.zeros(N)
  x2_dev_rand = np.zeros(N)
  t_dev_rand = np.zeros(N)

  for i in range(N):
    x1_train_rand[i] = x1_train[idx1[i]]
    x2_train_rand[i] = x2_train[idx1[i]]
    t_train_rand[i] = t_train[idx1[i]]
    x1_dev_rand[i] = x1_dev[idx1[i]]
    x2_dev_rand[i] = x2_dev[idx1[i]]
    t_dev_rand[i] = t_dev[idx1[i]]

  for i in range(N):
    for j in range(M):
      phi[i,j] = math.sqrt(x1_train_rand[i]**2 + x2_train_rand[i]**2)**j

  w = np.linalg.inv(phi.T@phi)@(phi.T)@(t_train_rand)

  # model
  def y3(x,y):
    sum = 0
    for i in range(M):
      sum += w[i]*((((x**2)+(y**2))**0.5)**i)
    return sum

  sum = 0

  for n in range(N):
    sum += (y3(x1_train_rand[n],x2_train_rand[n])-t_train_rand[n])**2

  E_RMS_train.append((sum/N)**0.5)

  sum = 0

  for n in range(N):
    sum += (y3(x1_dev_rand[n],x2_dev_rand[n])-t_dev_rand[n])**2

  E_RMS_dev.append((sum/N)**0.5)

  fig = plt.figure()
  
  # syntax for 3-D projection
  # ax = plt.axes(projection ='3d')
  
  # defining all 3 axes
  x = np.linspace(-1, 1, 100)
  y = np.linspace(-1, 1, 100)
  x,y = np.meshgrid(x,y)
  z = y3(x,y)

  # plotting
  fig = plt.figure(figsize=(6,6))
  ax = fig.gca(projection='3d')
  ax.plot_surface(x, y, z)  
  plt.show()

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot(degrees, E_RMS_train, color ="blue")
plt.show()

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot(degrees, E_RMS_dev, color ="purple")
plt.show()

M_opt = 4

test_size = [10,50,100,120,150,200]

for N in test_size:

  phi = np.zeros([N,M])

  idx1 = random.sample(range(N), N)
  idx2 = random.sample(range(N), N)
  x1_train_rand = np.zeros(N)
  x2_train_rand = np.zeros(N)
  t_train_rand = np.zeros(N)
  x1_dev_rand = np.zeros(N)
  x2_dev_rand = np.zeros(N)
  t_dev_rand = np.zeros(N)

  for i in range(N):
    x1_train_rand[i] = x1_train[idx1[i]]
    x2_train_rand[i] = x2_train[idx1[i]]
    t_train_rand[i] = t_train[idx1[i]]
    x1_dev_rand[i] = x1_dev[idx1[i]]
    x2_dev_rand[i] = x2_dev[idx1[i]]
    t_dev_rand[i] = t_dev[idx1[i]]

  for i in range(N):
    for j in range(M):
      phi[i,j] = math.sqrt(x1_train_rand[i]**2 + x2_train_rand[i]**2)**j

  w = np.linalg.inv(phi.T@phi)@(phi.T)@(t_train_rand)

  # model
  def y3(x,y):
    sum = 0
    for i in range(M):
      sum += w[i]*((((x**2)+(y**2))**0.5)**i)
    return sum

  # fig = plt.figure()
  
  # syntax for 3-D projection
  # ax = plt.axes(projection ='3d')
  
  # defining all 3 axes
  x = np.linspace(-1, 1, 100)
  y = np.linspace(-1, 1, 100)
  x,y = np.meshgrid(x,y)
  z = y3(x,y)

  # plotting
  fig = plt.figure(figsize=(6,6))
  ax = fig.gca(projection='3d')
  ax.plot_surface(x, y, z)  
  plt.show()

# Ridge regression for 2-D dataset

N = 200;

E_RMS_train = []
E_RMS_dev = []

model_complexity = [1,2,3,4,5,6,7]

for M in model_complexity:

  phi = np.zeros([N,M])
  lam = math.exp(-18)

  idx1 = random.sample(range(N), N)
  idx2 = random.sample(range(N), N)
  x1_train_rand = np.zeros(N)
  x2_train_rand = np.zeros(N)
  t_train_rand = np.zeros(N)
  x1_dev_rand = np.zeros(N)
  x2_dev_rand = np.zeros(N)
  t_dev_rand = np.zeros(N)

  for i in range(N):
    x1_train_rand[i] = x1_train[idx1[i]]
    x2_train_rand[i] = x2_train[idx1[i]]
    t_train_rand[i] = t_train[idx1[i]]
    x1_dev_rand[i] = x1_dev[idx2[i]]
    x2_dev_rand[i] = x2_dev[idx2[i]]
    t_dev_rand[i] = t_dev[idx2[i]]

  for i in range(N):
    for j in range(M):
      phi[i,j] = math.sqrt((x1_train_rand[i]**2)+(x2_train_rand[i]**2))**j

  w = np.linalg.inv(np.add(phi.T@phi,lam*np.eye(M)))@(phi.T)@(t_train_rand)

  # model
  def y4(x,y):
    sum = 0
    for i in range(M):
      sum += w[i]*((((x**2)+(y**2))**0.5)**i)     
    return sum + (lam/2)*np.sum(w**2)

  sum = 0

  for n in range(N):
    sum += (y4(x1_train_rand[n],x2_train_rand[n])-t_train_rand[n])**2

  E_RMS_train.append((sum/N)**0.5)

  sum = 0

  for n in range(N):
    sum += (y4(x1_dev_rand[n],x2_dev_rand[n])-t_dev_rand[n])**2

  E_RMS_dev.append((sum/N)**0.5)

  fig = plt.figure()
  
  # syntax for 3-D projection
  # ax = plt.axes(projection ='3d')

  x = np.linspace(-1, 1, 100)
  y = np.linspace(-1, 1, 100)
  x,y = np.meshgrid(x,y)
  z = y4(x,y)

  # plotting
  fig = plt.figure(figsize=(6,6))
  ax = fig.gca(projection='3d')
  ax.plot_surface(x, y, z)  
  plt.show()

x = np.linspace(-1, 1, 100)
y = np.linspace(-1, 1, 100)

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot(model_complexity, E_RMS_train, color ="blue")
plt.show()

# plotting
plt.xlabel("Model complexity")
plt.ylabel("Root Mean Squared Error")
plt.plot(model_complexity, E_RMS_dev, color ="purple")
plt.show()

M_opt = 4

E_RMS_train = []
E_RMS_dev = []

lambdas = [-math.inf,-35,-25,-20,0]

for lam in lambdas:

  lam = math.exp(lam)
  phi = np.zeros([N,M_opt])

  for i in range(N):
    for j in range(M_opt):
      phi[i,j] = math.sqrt((x1_train_rand[i]**2)+(x2_train_rand[i]**2))**j

  w = np.linalg.inv(np.add(phi.T@phi,lam*np.eye(M_opt)))@(phi.T)@(t_train_rand)

  # model
  def y4(x,y):
    sum = 0
    for i in range(M_opt):
      sum += w[i]*((((x**2)+(y**2))**0.5)**i)     
    return sum + (lam/2)*np.sum(w**2)

  sum = 0

  for n in range(N):
    sum += (y4(x1_train_rand[n],x2_train_rand[n])-t_train_rand[n])**2

  E_RMS_train.append((sum/N)**0.5)

  sum = 0

  for n in range(N):
    sum += (y4(x1_dev_rand[n],x2_dev_rand[n])-t_dev_rand[n])**2

  E_RMS_dev.append((sum/N)**0.5)

  fig = plt.figure()
  
  # syntax for 3-D projection
  # ax = plt.axes(projection ='3d')

  x = np.linspace(-1, 1, 100)
  y = np.linspace(-1, 1, 100)
  x,y = np.meshgrid(x,y)
  z = y4(x,y)

  # plotting
  fig = plt.figure(figsize=(6,6))
  ax = fig.gca(projection='3d')
  ax.plot_surface(x, y, z)  
  plt.show()

# plotting
plt.xlabel("ln(lambda)")
plt.ylabel("Root Mean Squared Error")
plt.plot(lambdas, E_RMS_train, color ="blue")
plt.show()

# plotting
plt.xlabel("ln(lambda)")
plt.ylabel("Root Mean Squared Error")
plt.plot(lambdas, E_RMS_dev, color ="purple")
plt.show()

lam_opt = math.exp(-20)

test_size = [10,50,100,120,150,200]

for N in test_size:

  phi = np.zeros([N,M_opt])

  idx1 = random.sample(range(N), N)
  idx2 = random.sample(range(N), N)
  x1_train_rand = np.zeros(N)
  x2_train_rand = np.zeros(N)
  t_train_rand = np.zeros(N)
  x1_dev_rand = np.zeros(N)
  x2_dev_rand = np.zeros(N)
  t_dev_rand = np.zeros(N)

  for i in range(N):
    x1_train_rand[i] = x1_train[idx1[i]]
    x2_train_rand[i] = x2_train[idx1[i]]
    t_train_rand[i] = t_train[idx1[i]]
    x1_dev_rand[i] = x1_dev[idx1[i]]
    x2_dev_rand[i] = x2_dev[idx1[i]]
    t_dev_rand[i] = t_dev[idx1[i]]

  for i in range(N):
    for j in range(M_opt):
      phi[i,j] = math.sqrt((x1_train_rand[i]**2)+(x2_train_rand[i]**2))**j

  w = np.linalg.inv(np.add(phi.T@phi,lam_opt*np.eye(M_opt)))@(phi.T)@(t_train_rand)

  # model
  def y4(x,y):
    sum = 0
    for i in range(M_opt):
      sum += w[i]*((((x**2)+(y**2))**0.5)**i)     
    return sum + (lam_opt/2)*np.sum(w**2)

  fig = plt.figure()
  
  # syntax for 3-D projection
  # ax = plt.axes(projection ='3d')

  x = np.linspace(-1, 1, 100)
  y = np.linspace(-1, 1, 100)
  x,y = np.meshgrid(x,y)
  z = y4(x,y)

  # plotting
  fig = plt.figure(figsize=(6,6))
  ax = fig.gca(projection='3d')
  ax.plot_surface(x, y, z)  
  plt.show()
