# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xkQMaubHHGQKrcE-MDsFW3kZwziJt6Lt
"""

import numpy as np
import os
import random
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve
from sklearn.metrics import det_curve

from google.colab import drive
drive.mount('/content/drive')

"""**Principal Component Analysis (PCA)**"""

# Mean estimation
def Mu(X):
  return np.sum(X,axis=0)/len(X)

# Covariance matrix estimation 
def Sigma(X,mu):
  N = len(X) 
  d = len(mu)
  X = np.reshape(X,(N,d,1))
  mu = np.reshape(mu,(d,1))
  sum = np.zeros((d,d))
  for n in range(N):
    sum += (X[n]-mu)@((X[n]-mu).T)
  return sum/(N-1)

def PCA(X1,K,X2):
  mu = Mu(X1)
  sigma = Sigma(X1,mu)
  eig_vals,eig_vecs = np.linalg.eig(sigma)
  seq = np.argsort(np.absolute(eig_vals))[::-1]
  eig_vecs = eig_vecs.T
  eig_vecs = eig_vecs[seq]
  return ((np.absolute(eig_vecs)[:K])@(X1.T)).T,((np.absolute(eig_vecs)[:K])@(X2.T)).T

"""**Linear Discriminant Analysis (LDA)**"""

# Calculation of within-class scatter matrix
def SW(X,mu):
  d = len(X[0][0])
  res = np.zeros((d,d))
  for clas in range(len(X)):
    for data in X[clas]:
      res += (np.array(data)-mu[clas])@((np.array(data)-mu[clas]).T)
  return res

# Calculation of between-class scatter matrix
def SB(X,mu,mu_overall):
  d = len(mu[0])
  res = np.zeros((d,d))
  for clas in range(len(mu)):
    res += len(X[clas])*(mu[clas]-mu_overall)@((mu[clas]-mu_overall).T)
  return res

def LDA(X1,X1_classwise,K,X2):
  mu = []
  mu_overall = Mu(X1)
  for clas in X1_classwise:
    mu.append(Mu(clas))
  sw = SW(X1_classwise,np.array(mu))
  # To make the matrix non-singular
  for i in range(len(sw)):
    sw[i,i] += 1e-9
  sb = SB(X1_classwise,np.array(mu),mu_overall)
  eig_vals,eig_vecs = np.linalg.eig(np.linalg.inv(sw)@sb)
  seq = np.argsort(np.absolute(eig_vals))[::-1]
  eig_vecs = eig_vecs.T
  eig_vecs = eig_vecs[seq]
  return ((np.absolute(eig_vecs)[:K])@(X1.T)).T,((np.absolute(eig_vecs)[:K])@(X2.T)).T

"""**K Nearest Neighbour (KNN) model**"""

def comp(x):
  return x[0]

# K Nearest Neighbours
def KNN(X,K,Train_data):
  distances = []
  for clas in range(len(Train_data)):
    for example in Train_data[clas]:
      distances.append([np.linalg.norm(np.array(X)-np.array(example)),clas])
  distances.sort(key=comp)
  ans = -1
  cnts = np.zeros(len(Train_data))
  for clas in range(len(Train_data)):
    cnt = 0
    for i in range(K):
      if distances[i][1] == clas:
        cnt+=1
    if cnt > ans:
      ans = clas
    elif cnt == ans:
      if random.randint(0,1) == 1:
        ans = clas
    cnts[clas] = cnt
  return cnts,ans

"""**Logistic Regression**"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from scipy.special import softmax
onehot_encoder = OneHotEncoder(sparse=False)
from sklearn.datasets import load_iris

def loss(X, Y, W):

    Z = - X @ W
    N = X.shape[0]
    loss = 1/N * (np.trace(X @ W @ Y.T) + np.sum(np.log(np.sum(np.exp(Z), axis=1))))
    return loss

def gradient(X, Y, W, mu):
    Z = - X @ W
    P = softmax(Z, axis=1)
    N = X.shape[0]
    gd = 1/N * (X.T @ (Y - P)) + 2 * mu * W
    return gd

def gradient_descent(X, Y, max_iter=1000, eta=0.1, mu=0.01):
    Y_onehot = onehot_encoder.fit_transform(Y.reshape(-1,1))
    W = np.zeros((X.shape[1], Y_onehot.shape[1]))
    step = 0
    step_lst = [] 
    loss_lst = []
    W_lst = []
 
    while step < max_iter:
        step += 1
        W -= eta * gradient(X, Y_onehot, W, mu)
        step_lst.append(step)
        W_lst.append(W)
        loss_lst.append(loss(X, Y_onehot, W))

    df = pd.DataFrame({
        'step': step_lst, 
        'loss': loss_lst
    })
    return df, W

class Multiclass:
    def fit(self, X, Y):
        self.loss_steps, self.W = gradient_descent(X, Y)

    def loss_plot(self):
        return self.loss_steps.plot(
            x='step', 
            y='loss',
            xlabel='step',
            ylabel='loss'
        )

    def predict(self, H):
        Z = - H @ self.W
        P = softmax(Z, axis=1)
        return np.argmax(P, axis=1),P

"""**Confusion Matrix**"""

import seaborn as sns
def conf_matrix(tc,pc):
  n = len(np.unique(tc))
  Con_Matrix1 = np.zeros((n,n))
  for i in range(len(tc)):
    Con_Matrix1[int(tc[i])-1][int(pc[i])-1]+=1
  
  c = []
  r = []
  s=0
  for i in range(len(Con_Matrix1)):
    c.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1[i])*100)
    r.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1.T[i])*100)
    s+=Con_Matrix1[i][i]

  r.append(s/np.sum(Con_Matrix1)*100)
    
  Con_Matrix1 = np.c_[Con_Matrix1,c]
  Con_Matrix1 = np.vstack((Con_Matrix1,r))

  classes = []
  for i in range(n):
    classes.append("class "+str(i+1))
  font = {'family': 'serif',
          'color':  'red',
          'weight': 'bold',
          'size': 16,
          }
  ax = sns.heatmap(Con_Matrix1, annot=True, fmt="g")
  ax.xaxis.set_ticklabels(classes)
  plt.title('Confusion Matrix',fontdict = font)
  ax.set_xlabel('Predicted',fontdict = font)
  ax.set_ylabel('True',fontdict = font)
  ax.yaxis.set_ticklabels(classes)
  plt.show()

"""**Synthetic dataset**"""

## Reading file into a numpy array
x1_train,x2_train,t_train = np.loadtxt("/content/drive/MyDrive/Synthetic_Data/4/train.txt", delimiter=',', unpack=True)
x1_dev,x2_dev,t_dev = np.loadtxt("/content/drive/MyDrive/Synthetic_Data/4/dev.txt", delimiter=',', unpack=True)

mean_train1 = np.mean(x1_train)
std_train1 = np.std(x1_train)

mean_train2 = np.mean(x2_train)
std_train2 = np.std(x2_train)

mean_dev1 = np.mean(x1_dev)
std_dev1 = np.std(x1_dev)

mean_dev2 = np.mean(x2_dev)
std_dev2 = np.std(x2_dev)

for n in range(len(x1_train)):
  x1_train[n] = (x1_train[n]-mean_train1)/std_train1
  x2_train[n] = (x2_train[n]-mean_train2)/std_train2

for n in range(len(x1_dev)):
  x1_dev[n] = (x1_dev[n]-mean_dev1)/std_dev1
  x2_dev[n] = (x2_dev[n]-mean_dev2)/std_dev2

x_train = [x1_train,x2_train]
x_train = np.asarray(x_train)
x_train = x_train.T

x_dev = [x1_dev,x2_dev]
x_dev = np.asarray(x_dev)
x_dev = x_dev.T

x_train_PCA,x_dev_PCA = PCA(x_train,1,x_dev)

half_train_size = 1250
half_dev_size = 500

x_train_classwise = [x_train[:half_train_size,:],x_train[half_train_size:,:]]
x_train_classwise = np.asarray(x_train_classwise)

x_train_LDA,x_dev_LDA = LDA(x_train,x_train_classwise,1,x_dev)

"""ANN"""

from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

"""ANN - Synthetic"""

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    h1 = keras.layers.Dense(24,activation = 'relu')(input_layer)

    output_layer = keras.layers.Dense(2, activation="softmax")(h1)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)

model = make_model(input_shape=x_train[0].shape)

t_train = t_train.astype(int) - 1

from sklearn.model_selection import train_test_split
XTraining1, XValidation1, YTraining1, YValidation1 = train_test_split(x_train,t_train,stratify=t_train,test_size=0.25)

epochs = 100
batch_size = 512

model.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
history = model.fit(
    XTraining1,YTraining1,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidation1,YValidation1)
)

result = model.predict(x_dev)

result

model.evaluate(x_dev,t_dev-1)

y_pred =  np.argmax(result, axis=1)

conf_matrix(y_pred,t_dev-1)

"""PCA ANN Synthetic"""

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    h1 = keras.layers.Dense(24,activation = 'relu')(input_layer)

    output_layer = keras.layers.Dense(2, activation="softmax")(h1)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)

modelp1 = make_model(input_shape=x_train_PCA[0].shape)

from sklearn.model_selection import train_test_split
XTrainingp1, XValidationp1, YTrainingp1, YValidationp1 = train_test_split(x_train_PCA,t_train,stratify=t_train,test_size=0.25)

epochs = 100
batch_size = 512

modelp1.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
historyp1 = modelp1.fit(
    XTrainingp1,YTrainingp1,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationp1,YValidationp1)
)

resultp = modelp1.predict(x_dev_PCA)

result.shape

modelp1.evaluate(x_dev_PCA,t_dev-1)

y_pred =  np.argmax(resultp, axis=1)
conf_matrix(y_pred,t_dev-1)

"""ANN - LDA - Synthetic"""

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    h1 = keras.layers.Dense(24,activation = 'relu')(input_layer)

    output_layer = keras.layers.Dense(2, activation="softmax")(h1)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)

modell1 = make_model(input_shape=x_train_LDA[0].shape)

XTrainingl1, XValidationl1, YTrainingl1, YValidationl1 = train_test_split(x_train_LDA,t_train,stratify=t_train,test_size=0.25)

epochs = 100
batch_size = 512

modell1.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
historyl1 = modell1.fit(
    XTrainingl1,YTrainingl1,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationl1,YValidationl1)
)

resultl = modell1.predict(x_dev_LDA)

modell1.evaluate(x_dev_LDA,t_dev-1)

y_pred =  np.argmax(resultl, axis=1)
conf_matrix(y_pred,t_dev-1)

"""Evaluation"""

M = 1000
N = 2 
s = result
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

M = 1000
N = 2 
s = resultp
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11P, TPR11P, color ="green")
plt.show()

M = 1000
N = 2 
s = resultl
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11l, TPR11l, color ="green")
plt.show()

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

target_class = 1

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if t_dev[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = result[i,target_class-1]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if t_dev[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = resultp[i,target_class-1]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if t_dev[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = resultl[i,target_class-1]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""SVM - Synthetic"""

import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf.fit(x_train, t_train)

x_dev_pred = clf.predict(x_dev)

x_dev_proba = clf.predict_proba(x_dev)

conf_matrix(x_dev_pred,t_dev-1)

"""SVM - PCA - Synthetic"""

clfp = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clfp.fit(x_train_PCA, t_train)

x_dev_PCA_pred = clfp.predict(x_dev_PCA)

x_dev_PCA_proba = clfp.predict_proba(x_dev_PCA)

conf_matrix(x_dev_PCA_pred,t_dev-1)

"""SVM - LDA - Synthetic"""

clfl = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clfl.fit(x_train_LDA, t_train)

x_dev_LDA_pred = clfl.predict(x_dev_LDA)

x_dev_LDA_proba = clfl.predict_proba(x_dev_LDA)

conf_matrix(x_dev_LDA_pred,t_dev-1)

"""Evalution"""

M = 1000
N = 2 
s = x_dev_proba
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

M = 1000
N = 2 
s = x_dev_PCA_proba
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11P, TPR11P, color ="green")
plt.show()

M = 1000
N = 2 
s = x_dev_LDA_proba
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11l, TPR11l, color ="green")
plt.show()

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

target_class = 1

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if t_dev[i]-1 == target_class:
    y_true1[i] = 1
  y_scores1[i] = x_dev_proba[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if t_dev[i]-1 == target_class:
    y_true2[i] = 1
  y_scores2[i] = x_dev_PCA_proba[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if t_dev[i]-1 == target_class:
    y_true3[i] = 1
  y_scores3[i] = x_dev_LDA_proba[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""**Logistic** **Regression**"""

model_rand=Multiclass()
model_rand.fit(x_train,t_train)
y_pred,y_proba = model_rand.predict(x_dev)

conf_matrix(y_pred,t_dev-1)

"""PCA"""

model_rand1=Multiclass()
model_rand1.fit(x_train_PCA,t_train)
y_predp,y_probap = model_rand1.predict(x_dev_PCA)

conf_matrix(y_predp,t_dev-1)

"""LDA"""

model_rand2=Multiclass()
model_rand2.fit(x_train_LDA,t_train)
y_predl,y_probal = model_rand2.predict(x_dev_LDA)

conf_matrix(y_predl,t_dev-1)

"""Evaluation"""

M = 1000
N = 2 
s = y_proba
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

M = 1000
N = 2 
s = y_probap
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11P, TPR11P, color ="green")
plt.show()

M = 1000
N = 2 
s = y_probal
li = t_dev-1
min = np.amin(s)
max = np.amax(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11l, TPR11l, color ="green")
plt.show()

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if t_dev[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = y_proba[i,target_class-1]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if t_dev[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = y_probap[i,target_class-1]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if t_dev[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = y_probal[i,target_class-1]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""**Image dataset**"""

## Reading file into a numpy array

Train_data = []
Train_datay = []
Dev_data = []
Dev_datay = []


X1=[]
os.chdir('/content/drive/MyDrive/Features/coast/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/coast/dev'}/{file}" 
    X1.append(np.loadtxt(file_path))
Dev_data.append(X1)
Dev_datay = Dev_datay + len(X1)*[0]

Y1=[]
os.chdir('/content/drive/MyDrive/Features/coast/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/coast/train'}/{file}" 
    Y1.append(np.loadtxt(file_path)) 
Train_data.append(Y1)
Train_datay = Train_datay + len(Y1)*[0]

X2=[]
os.chdir('/content/drive/MyDrive/Features/forest/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/forest/dev'}/{file}" 
    X2.append(np.loadtxt(file_path))
Dev_data.append(X2)
Dev_datay = Dev_datay + len(X2)*[1]
Y2=[]
os.chdir('/content/drive/MyDrive/Features/forest/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/forest/train'}/{file}" 
    Y2.append(np.loadtxt(file_path))
Train_data.append(Y2)
Train_datay = Train_datay + len(Y2)*[1]
X3=[]
os.chdir('/content/drive/MyDrive/Features/highway/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/highway/dev'}/{file}" 
    X3.append(np.loadtxt(file_path))
Dev_data.append(X3)
Dev_datay = Dev_datay + len(X3)*[2]
Y3=[]
os.chdir('/content/drive/MyDrive/Features/highway/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/highway/train'}/{file}" 
    Y3.append(np.loadtxt(file_path))
Train_data.append(Y3)
Train_datay = Train_datay + len(Y3)*[2]
X4=[]
os.chdir('/content/drive/MyDrive/Features/mountain/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/mountain/dev'}/{file}" 
    X4.append(np.loadtxt(file_path))
Dev_data.append(X4)
Dev_datay = Dev_datay + len(X4)*[3]
Y4=[]
os.chdir('/content/drive/MyDrive/Features/mountain/train')
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/mountain/train'}/{file}" 
    Y4.append(np.loadtxt(file_path))
Train_data.append(Y4)
Train_datay = Train_datay + len(Y4)*[3]
X5=[]
os.chdir('/content/drive/MyDrive/Features/opencountry/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/opencountry/dev'}/{file}" 
    X5.append(np.loadtxt(file_path))
Dev_data.append(X5)
Dev_datay = Dev_datay + len(X5)*[4]
Y5=[]
os.chdir('/content/drive/MyDrive/Features/opencountry/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/opencountry/train'}/{file}" 
    Y5.append(np.loadtxt(file_path))
Train_data.append(Y5)
Train_datay = Train_datay + len(Y5)*[4]

Train_data1 = []
for clas in Train_data:
  A = []
  for image in clas:
    A.append(image)
  Train_data1.append(np.asarray(A))

Train_data2 = []
for i in Train_data1:
  for c in i:
    Train_data2.append(c)

Train_data2 = np.asarray(Train_data2)

Train_datay = np.asarray(Train_datay)
Dev_datay = np.asarray(Dev_datay)

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    output_layer = keras.layers.Dense(5, activation="softmax")(gap)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


model1 = make_model(input_shape=Train_data2[0].shape)

from sklearn.model_selection import train_test_split
XTraining, XValidation, YTraining, YValidation = train_test_split(Train_data2,Train_datay,stratify=Train_datay,test_size=0.4) # before model building

epochs = 200
batch_size = 128

model1.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.00005),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
history = model1.fit(
    XTraining,YTraining,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidation,YValidation)
)

Dev_data1 = []
for clas in Dev_data:
  for image in clas:
    Dev_data1.append(image)

Dev_data1 = np.asarray(Dev_data1)

result1 = model1.predict(Dev_data1)

result1

model1.evaluate(Dev_data1,Dev_datay)

y_pred = np.argmax(result1,axis=1)
conf_matrix(y_pred,Dev_datay)

"""PCA - ANN - Image"""

Train_data2p = np.reshape(Train_data2, (1210,36*23))

Dev_data1p = np.reshape(Dev_data1,(348,36*23))

Train_data_PCA,Dev_data_PCA = PCA(Train_data2p,36*4,Dev_data1p)

Train_data_PCA1 = np.reshape(Train_data_PCA,(1210,36*4,1))
Dev_data_PCA1 = np.reshape(Dev_data_PCA,(348,36*4,1))

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    h1 = keras.layers.Dense(24,activation = 'relu')(gap)

    output_layer = keras.layers.Dense(5, activation="softmax")(h1)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


modelp2 = make_model(input_shape=Train_data_PCA1[0].shape)

XTrainingp2, XValidationp2, YTrainingp2, YValidationp2 = train_test_split(Train_data_PCA1,Train_datay,stratify=Train_datay,test_size=0.25) # before model building

epochs = 300
batch_size = 128

modelp2.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.00005),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
history = modelp2.fit(
    XTrainingp2,YTrainingp2,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationp2,YValidationp2)
)

resultp1 = modelp2.predict(Dev_data_PCA1)

modelp2.evaluate(Dev_data_PCA1,Dev_datay)

y_pred = np.argmax(resultp1,axis=1)
conf_matrix(y_pred,Dev_datay)

"""

LDA - ANN - Image

"""

Train_data4 = [Train_data2p[:73],Train_data2p[73:139],Train_data2p[139:191],Train_data2p[191:266],Train_data2p[266:348]]

Train_data_LDA,Dev_data_LDA = LDA(Train_data2p,Train_data4,36*4,Dev_data1p)

Train_data_LDA1 = np.reshape(Train_data_PCA,(1210,36,4))
Dev_data_LDA1 = np.reshape(Dev_data_PCA,(348,36,4))

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    output_layer = keras.layers.Dense(5, activation="softmax")(gap)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


modell2 = make_model(input_shape=Train_data_LDA1[0].shape)

XTrainingl2, XValidationl2, YTrainingl2, YValidationl2 = train_test_split(Train_data_LDA1,Train_datay,stratify=Train_datay,test_size=0.2)

epochs = 400
batch_size = 128

modell2.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.00005),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
historyl2 = modell2.fit(
    XTrainingl2,YTrainingl2,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationl2,YValidationl2)
)

resultl1 = modell2.predict(Dev_data_LDA1)

modell2.evaluate(Dev_data_LDA1,Dev_datay)

y_pred = np.argmax(resultl1,axis=1)
conf_matrix(y_pred,Dev_datay)

"""Evaluation"""

result1.shape

M = 348
N = 5 
s = resultp1
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11P, TPR11P, color ="green")
plt.show()

M = 348
N = 5 
s = result1
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

M = 348
N = 5 
s = resultl1
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11l, TPR11l, color ="green")
plt.show()

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = result1[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = resultp1[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = resultl1[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

"""SVM"""

Train_data3 = []
for i in Train_data2:
  c = np.reshape(i,-1)
  Train_data3.append(c)

Train_data3 = np.asarray(Train_data3)

Dev_data2 = []
for i in Dev_data1:
  c = np.reshape(i,-1)
  Dev_data2.append(c)

Dev_data2 = np.asarray(Dev_data2)

clf2 = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf2.fit(Train_data3, Train_datay)

Dev_data2_pred = clf2.predict(Dev_data2).astype(int)

Dev_data_prob = clf2.predict_proba(Dev_data2)

conf_matrix(Dev_datay, Dev_data2_pred)

"""SVM -PCA - Image"""

Train_data3_PCA,Dev_data3_PCA = PCA(Train_data3,36*4,Dev_data2)

clf2p = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf2p.fit(Train_data3_PCA, Train_datay)

Dev_data2p_pred = clf2p.predict(Dev_data3_PCA)

Dev_data2p_proba = clf2p.predict_proba(Dev_data3_PCA)

from sklearn.metrics import accuracy_score
accuracy_score(Dev_datay, Dev_data2p_pred)

conf_matrix(Dev_datay, Dev_data2p_pred)

"""SVM - LDA - image"""

clf2l = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf2l.fit(Train_data_LDA, Train_datay)

Dev_data2l_pred = clf2l.predict(Dev_data_LDA)

Dev_data2l_proba = clf2l.predict_proba(Dev_data_LDA)

accuracy_score(Dev_datay, Dev_data2l_pred)

conf_matrix(Dev_datay, Dev_data2l_pred)

"""Evaluation"""

M = 348
N = 5 
s = Dev_data_prob
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

M = 348
N = 5 
s = Dev_data2p_proba
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11P, TPR11P, color ="green")
plt.show()

M = 348
N = 5 
s = Dev_data2l_proba
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11l, TPR11l, color ="green")
plt.show()

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = Dev_data_prob[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = Dev_data2p_proba[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = Dev_data2l_proba[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""**Logistic** **Regression** """

from sklearn.preprocessing import MinMaxScaler 
M = MinMaxScaler()
Train_data3s = M.fit_transform(Train_data3)
Dev_data2s = M.fit_transform(Dev_data2)

model_rand4=Multiclass()
model_rand4.fit(Train_data3s, Train_datay)
y_predi,y_probai = model_rand4.predict(Dev_data2s)

conf_matrix(Dev_datay, y_predi)

"""PCA"""

Train_data3_PCAs = M.fit_transform(Train_data3_PCA)
Dev_data3_PCAs = M.fit_transform(Dev_data3_PCA)

model_rand5=Multiclass()
model_rand5.fit(Train_data3_PCAs, Train_datay)
y_predip,y_probaip = model_rand5.predict(Dev_data3_PCAs)

conf_matrix(Dev_datay, y_predip)

"""LDA"""

Train_data_LDAs = M.fit_transform(Train_data_LDA)
Dev_data_LDAs = M.fit_transform(Dev_data_LDA)

model_rand6=Multiclass()
model_rand6.fit(Train_data_LDAs, Train_datay)
y_predil,y_probail = model_rand6.predict(Dev_data_LDAs)

conf_matrix(Dev_datay, y_predil)

"""Evaluation"""

M = 348
N = 5 
s = y_probai
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11, TPR11, color ="green")
plt.show()

M = 348
N = 5 
s = y_probaip
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate



# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11P, TPR11P, color ="green")
plt.show()

M = 348
N = 5 
s = y_probail
li = Dev_datay
min = np.amin(s)
max = np.amax(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

print(s)
print(FPR11)  
print(TPR11) 

# plotting
plt.title("ROC curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.plot(FPR11l, TPR11l, color ="green")
plt.show()

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = y_probai[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = y_probaip[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev_datay[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = y_probail[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""..

**Isolated digits dataset**
"""

## Reading file into a numpy array

Training_data = []
Training_datay = []
X1=[]

os.chdir('/content/drive/MyDrive/Isolated_Digits/3/train')

# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/3/train'}/{file}" 
    X1.append(np.loadtxt(file_path, skiprows=1))
      
Training_data.append(X1)
Training_datay = Training_datay + len(X1)*[0]

X2=[]

os.chdir('/content/drive/MyDrive/Isolated_Digits/4/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/4/train'}/{file}" 
    X2.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X2)
Training_datay = Training_datay + len(X2)*[1]
X3=[]

os.chdir('/content/drive/MyDrive/Isolated_Digits/5/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/5/train'}/{file}" 
    X3.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X3)
Training_datay = Training_datay + len(X2)*[2]
X4=[]

os.chdir('/content/drive/MyDrive/Isolated_Digits/7/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/7/train'}/{file}" 
    X4.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X4)
Training_datay = Training_datay + len(X4)*[3]


X5=[]

os.chdir('/content/drive/MyDrive/Isolated_Digits/o/train')

for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/o/train'}/{file}" 
    X5.append(np.loadtxt(file_path, skiprows=1))

Training_data.append(X5)
Training_datay = Training_datay + len(X5)*[4]

x_3 = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/3/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/3/dev'}/{file}" 
    x_3.append(np.loadtxt(file_path, skiprows=1))

x_4=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/4/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/4/dev'}/{file}" 
    x_4.append(np.loadtxt(file_path, skiprows=1))

x_5 = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/5/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/5/dev'}/{file}" 
    x_5.append(np.loadtxt(file_path, skiprows=1))

x_7=[]
os.chdir('/content/drive/MyDrive/Isolated_Digits/7/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/7/dev'}/{file}" 
    x_7.append(np.loadtxt(file_path, skiprows=1))

x_o = []
os.chdir('/content/drive/MyDrive/Isolated_Digits/o/dev')
# iterate through all file
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/Isolated_Digits/o/dev'}/{file}" 
    x_o.append(np.loadtxt(file_path, skiprows=1))

Training_datay = np.asarray(Training_datay)

Dev1_datay = len(x_3)*[0]+len(x_4)*[1]+len(x_5)*[2]+len(x_7)*[3]+len(x_o)*[4]

Dev1_datay = np.asarray(Dev1_datay)

Dev1_data = [x_3,x_4,x_5,x_7,x_o]

m = 0
for i in range(len(Training_data)):
  for j in range(len(Training_data[i])):
    if (len(Training_data[i][j])>m):
      m = len(Training_data[i][j])

m1 = 0
for i in range(len(Dev1_data)):
  for j in range(len(Dev1_data[i])):
    if (len(Dev1_data[i][j])>m1):
      m1 = len(Dev1_data[i][j])

m>m1 == 0

from scipy.signal import resample

Training_data1 = []
for i in range(len(Training_data)):
  for j in range(len(Training_data[i])):
    Training_data1.append(resample(Training_data[i][j],m1))

Training_data1 = np.asarray(Training_data1)

Training_data1.shape

Dev1_data1 = []
for i in range(len(Dev1_data)):
  for j in range(len(Dev1_data[i])):
      Dev1_data1.append(resample(Dev1_data[i][j],m1))

Dev1_data1 = np.asarray(Dev1_data1)

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    output_layer = keras.layers.Dense(5, activation="softmax")(gap)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


model2 = make_model(input_shape=Training_data1[0].shape)

XTraining2, XValidation2, YTraining2, YValidation2 = train_test_split(Training_data1,Training_datay,stratify=Training_datay,test_size=0.4) # before model building

epochs = 300
batch_size = 128

model2.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.00005),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
history = model2.fit(
    XTraining2,YTraining2,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidation2,YValidation2)
)

model2.evaluate(Dev1_data1,Dev1_datay)

result2 = model2.predict(Dev1_data1)

result2

y_pred = np.argmax(result2,axis=1)
conf_matrix(Dev1_datay,y_pred)

"""SVM"""

Training_data3 = []
for i in Training_data1:
  c = np.reshape(i,-1)
  Training_data3.append(c)

Training_data3 = np.asarray(Training_data3)

Dev1_data2 = []
for i in Dev1_data1:
  c = np.reshape(i,-1)
  Dev1_data2.append(c)

Dev1_data2 = np.asarray(Dev1_data2)

clf3 = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf3.fit(Training_data3, Training_datay)

Dev1_data2_pred = clf3.predict(Dev1_data2)

Dev1_data2_proba = clf3.predict_proba(Dev1_data2)

accuracy_score(Dev1_datay,Dev1_data2_pred)

conf_matrix(Dev1_datay,Dev1_data2_pred)

"""ANN - PCA - Isolated Digits"""

Train_data4_PCA1,Dev_data4_PCA1 = PCA(Training_data3,183*4,Dev1_data2)

Train_data4_PCA = np.reshape(Train_data4_PCA1,(len(Train_data4_PCA1),183,4))
Dev_data4_PCA = np.reshape(Dev_data4_PCA1,(len(Dev_data4_PCA1),183,4))

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=4, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    output_layer = keras.layers.Dense(5, activation="softmax")(gap)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


modelp3 = make_model(input_shape=Train_data4_PCA[0].shape)

XTrainingp4, XValidationp4, YTrainingp4, YValidationp4 = train_test_split(Train_data4_PCA,Training_datay,stratify=Training_datay,test_size=0.2) # before model building

epochs = 400
batch_size = 128

modelp3.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.0001),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
historyp3 = modelp3.fit(
    XTrainingp4,YTrainingp4,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationp4,YValidationp4)
)

ressultp4 = modelp3.predict(Dev_data4_PCA)

modelp3.evaluate(Dev_data4_PCA,Dev1_datay)

y_pred = np.argmax(ressultp4,axis=1)
conf_matrix(Dev1_datay,y_pred)

"""SVM - PCA - isolated """

Train_data4_PCA11 = abs(Train_data4_PCA1)
Dev_data4_PCA11 = abs(Dev_data4_PCA1)

Train_data4_PCA11.shape

clf3p = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf3p.fit(Train_data4_PCA11, Training_datay)

Dev_data4_PCA11_pred = clf3p.predict(Dev_data4_PCA11)

Dev_data4_PCA11_proba = clf3p.predict_proba(Dev_data4_PCA11)

accuracy_score(Dev1_datay,Dev_data4_PCA11_pred)

conf_matrix(Dev1_datay,Dev_data4_PCA11_pred)

"""ANN - LDA - Isolated"""

Training_data3classwise = [Training_data3[0:39],Training_data3[39:78],Training_data3[78:117],Training_data3[117:156],Training_data3[156:]]

Train_data_LDA11,Dev_data_LDA11 = LDA(Training_data3,Training_data3classwise,183*4,Dev1_data2)

Train_data_LDA1 = np.reshape(Train_data_LDA11,(len(Train_data_LDA11),183,4))
Dev_data_LDA1 = np.reshape(Dev_data_LDA11,(len(Dev_data_LDA11),183,4))

modell3 = make_model(input_shape=Train_data_LDA1[0].shape)

XTrainingl4, XValidationl4, YTrainingl4, YValidationl4 = train_test_split(Train_data_LDA1,Training_datay,stratify=Training_datay,test_size=0.2) # before model building

epochs = 300
batch_size = 128

modell3.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.00005),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
historyl3 = modell3.fit(
    XTrainingl4,YTrainingl4,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationl4,YValidationl4)
)

ressultl4 = modell3.predict(Dev_data_LDA1)

modell3.evaluate(Dev_data_LDA1,Dev1_datay)

y_pred = np.argmax(ressultl4,axis=1)
conf_matrix(Dev1_datay,y_pred)

"""SVM - LDA - Isolated"""

clf3l = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf3l.fit(Train_data_LDA11, Training_datay)

Dev_data_LDA1_pred = clf3l.predict(Dev_data_LDA11)

Dev_data_LDA1_proba = clf3l.predict_proba(Dev_data_LDA11)

accuracy_score(Dev_data_LDA1_pred,Dev1_datay)

conf_matrix(Dev1_datay,Dev_data_LDA1_pred)

"""Evaluation"""

result2.shape

M = 60
N = 5 
s = result2
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

M = 60
N = 5 
s = ressultp4
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate

M = 60
N = 5 
s = ressultl4
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = result2[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = ressultp4[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = ressultl4[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""SVM Evaluation"""

M = 60
N = 5 
s = Dev1_data2_proba
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

M = 60
N = 5 
s = Dev_data4_PCA11_proba
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate

M = 60
N = 5 
s = Dev_data_LDA1_proba
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = Dev1_data2_proba[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = Dev_data4_PCA11_proba[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = Dev_data_LDA1_proba[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

"""**Logistic Regression**"""

model_rand7=Multiclass()
model_rand7.fit(Training_data3, Training_datay)
y_predis,y_probais = model_rand7.predict(Dev1_data2)

y_predis.shape

conf_matrix(Dev1_datay,y_predis)

"""PCA"""

model_rand8=Multiclass()
model_rand8.fit(Train_data4_PCA1, Training_datay)
y_predisp,y_probaisp = model_rand8.predict(Dev_data4_PCA1)

conf_matrix(Dev1_datay,y_predisp)

"""LDA"""

model_rand9=Multiclass()
model_rand9.fit(Train_data_LDA11, Training_datay)
y_predisl,y_probaisl = model_rand9.predict(Dev_data_LDA11)

conf_matrix(Dev1_datay,y_predisl)

"""Evaluation"""

M = 60
N = 5 
s = y_probais
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

M = 60
N = 5 
s = y_probaisp
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate

M = 60
N = 5 
s = y_probaisl
li = Dev1_datay
min = np.min(s)
max = np.max(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = y_probais[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = y_probaisp[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev1_datay[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = y_probaisl[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

"""..

**Handwritten character dataset**
"""

Train_data_digits = []
Train_data_digitsy = []
X1=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X1.append(K)
Train_data_digits.append(X1)
Train_data_digitsy = Train_data_digitsy + len(X1)*[0]

X2=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X2.append(K)
Train_data_digits.append(X2)
Train_data_digitsy = Train_data_digitsy + len(X2)*[1]
X3=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X3.append(K)
Train_data_digits.append(X3)
Train_data_digitsy = Train_data_digitsy + len(X3)*[2]
X4=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X4.append(K)
Train_data_digits.append(X4)
Train_data_digitsy = Train_data_digitsy + len(X4)*[3]
X5=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X5.append(K)
Train_data_digits.append(X5)
Train_data_digitsy = Train_data_digitsy + len(X5)*[4]

Dev1=[]
Dev1y = []
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev1.append(K)
Dev1y = Dev1y + len(Dev1)*[0]
Dev2=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev2.append(K)
Dev1y = Dev1y + len(Dev2)*[1]
Dev3=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev3.append(K)
Dev1y = Dev1y + len(Dev3)*[2]
Dev4=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev4.append(K)
Dev1y = Dev1y + len(Dev4)*[3]
Dev5=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev5.append(K)
Dev1y = Dev1y + len(Dev5)*[4]

Dev_data_digits = [Dev1,Dev2,Dev3,Dev4,Dev5]

Train_data_digitsy = np.asarray(Train_data_digitsy)
Dev1y = np.asarray(Dev1y)

m = 0
for i in range(len(Train_data_digits)):
  for j in range(len(Train_data_digits[i])):
    if (len(Train_data_digits[i][j])>m):
      m = len(Train_data_digits[i][j])

m1 = 0
for i in range(len(Dev_data_digits)):
  for j in range(len(Dev_data_digits[i])):
    if (len(Dev_data_digits)>m1):
      m = len(Dev_data_digits[i][j])

m>m1 == 0

Train_data_digits1 = []
for i in range(len(Train_data_digits)):
  for j in range(len(Train_data_digits[i])):
      Train_data_digits1.append(resample(Train_data_digits[i][j],m))

Dev_data_digits1 = []
for i in range(len(Dev_data_digits)):
  for j in range(len(Dev_data_digits[i])):
      Dev_data_digits1.append(resample(Dev_data_digits[i][j],m))

Train_data_digits1 = np.asarray(Train_data_digits1)
Dev_data_digits1 = np.asarray(Dev_data_digits1)

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    output_layer = keras.layers.Dense(5, activation="softmax")(gap)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


model3 = make_model(input_shape=Train_data_digits1[0].shape)

XTraining3, XValidation3, YTraining3, YValidation3 = train_test_split(Train_data_digits1,Train_data_digitsy,stratify=Train_data_digitsy,test_size=0.4) # before model building

epochs = 400
batch_size = 64

model3.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.00005),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
history = model3.fit(
    XTraining3,YTraining3,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidation3,YValidation3)
)

result4 = model3.predict(Dev_data_digits1)

model3.evaluate(Dev_data_digits1,Dev1y)

y_pred = np.argmax(result4,axis =1)
conf_matrix(Dev1y , y_pred)

"""SVM"""

Training_data4 = []
for i in Train_data_digits1:
  c = np.reshape(i,-1)
  Training_data4.append(c)

Training_data4 = np.asarray(Training_data4)

Dev_data4 = []
for i in Dev_data_digits1:
  c = np.reshape(i,-1)
  Dev_data4.append(c)

Dev_data4 = np.asarray(Dev_data4)

clf5 = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clf5.fit(Training_data4, Train_data_digitsy)

Dev_data4_pred = clf5.predict(Dev_data4)

Dev_data4_proba = clf5.predict_proba(Dev_data4)

accuracy_score(Dev_data4_pred,Dev1y)

conf_matrix(Dev_data4_pred,Dev1y)

"""Logistic Regression """

model_randH=Multiclass()
model_randH.fit(Training_data4, Train_data_digitsy)
y_predHs,y_probaHs = model_randH.predict(Dev_data4)

conf_matrix(y_predHs,Dev1y)

"""PCA - ANN - Handwritten"""

Train_data5_PCA1,Dev_data5_PCA1 = PCA(Training_data4,69,Dev_data4)

Train_data5_PCA = np.reshape(Train_data5_PCA1,(len(Train_data5_PCA1),69,1))
Dev_data5_PCA = np.reshape(Dev_data5_PCA1,(len(Dev_data5_PCA1),69,1))

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=16, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    output_layer = keras.layers.Dense(5, activation="softmax")(gap)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


modelp4 = make_model(input_shape=Train_data5_PCA[0].shape)

XTrainingp5, XValidationp5, YTrainingp5, YValidationp5 = train_test_split(Train_data5_PCA,Train_data_digitsy,stratify=Train_data_digitsy,test_size=0.2) # before model building

epochs = 200
batch_size = 128

modelp4.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.0005),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
historyp4 = modelp4.fit(
    XTrainingp5,YTrainingp5,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationp5,YValidationp5)
)

resultp5 = modelp4.predict(Dev_data5_PCA)

modelp4.evaluate(Dev_data5_PCA,Dev1y)

y_pred = np.argmax(resultp5,axis =1)
conf_matrix(Dev1y , y_pred)

"""SVM - PCA - Handwritten"""

clfp5 = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clfp5.fit(Train_data5_PCA1, Train_data_digitsy)

Dev_datap5_pred = clfp5.predict(Dev_data5_PCA1)

Dev_datap5_proba = clfp5.predict_proba(Dev_data5_PCA1)

accuracy_score(Dev_datap5_pred,Dev1y)

conf_matrix(Dev_datap5_pred,Dev1y)

"""Logistic Regression"""

model_randHp=Multiclass()
model_randHp.fit(Train_data5_PCA1, Train_data_digitsy)
y_predHp,y_probaHp = model_randHp.predict(Dev_data5_PCA1)

conf_matrix(y_predHp,Dev1y)

"""ANN - LDA - Handwritten"""

Training_data4classwise = [Training_data4[:69],Training_data4[69:139],Training_data4[139:206],Training_data4[206:276],Training_data4[276:345]]

Train_data_LDA2,Dev_data_LDA2 = LDA(Training_data4,Training_data4classwise,69,Dev_data4)

Train_data_LDA22 = np.reshape(Train_data_LDA2,(len(Train_data_LDA2),69,1))
Dev_data_LDA22 = np.reshape(Dev_data_LDA2,(len(Dev_data_LDA2),69,1))

modell4 = make_model(input_shape=Train_data_LDA22[0].shape)

XTrainingl5, XValidationl5, YTrainingl5, YValidationl5 = train_test_split(Train_data_LDA22,Train_data_digitsy,stratify=Train_data_digitsy,test_size=0.2) # before model building

epochs = 400
batch_size = 128

modell4.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.01),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
historyp4 = modell4.fit(
    XTrainingl5,YTrainingl5,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(XValidationl5,YValidationl5)
)

resultl5 = modell4.predict(Dev_data_LDA22)

modell4.evaluate(Dev_data_LDA22,Dev1y)

y_pred = np.argmax(resultl5,axis =1)
conf_matrix(Dev1y , y_pred)

"""SVM - LDA - handwritten"""

clfl5 = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
clfl5.fit(Train_data_LDA2, Train_data_digitsy)

Dev_datal5_pred = clfl5.predict(Dev_data_LDA2)

Dev_datal5_proba = clfl5.predict_proba(Dev_data_LDA2)

accuracy_score(Dev_datal5_pred,Dev1y)

conf_matrix(Dev_datal5_pred,Dev1y)

"""Logistic Regression"""

model_randHl=Multiclass()
model_randHl.fit(Train_data_LDA2, Train_data_digitsy)
y_predHl,y_probaHl = model_randHl.predict(Dev_data_LDA2)

conf_matrix(y_predHl,Dev1y)

"""Evaluation """

M = 100
N = 5 
s = result4
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

M = 100
N = 5 
s = resultp5
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate

M = 100
N = 5 
s = resultl5
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = result4[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = resultp5[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = resultl5[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

"""SVM Evaluation"""

M = 100
N = 5 
s = Dev_data4_proba
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

M = 100
N = 5 
s = Dev_datap5_proba
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate

M = 100
N = 5 
s = Dev_datal5_proba
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = Dev_data4_proba[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = Dev_datap5_proba[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = Dev_datal5_proba[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

"""Logistic Regression"""

M = 100
N = 5 
s = y_probaHs
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11 = []
FPR11 = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11.append(TP/(TP+FN))  # True positive rate
  FPR11.append(FP/(FP+TN))  # False positive rate

M = 100
N = 5 
s = y_probaHp
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11P = []
FPR11P = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11P.append(TP/(TP+FN))  # True positive rate
  FPR11P.append(FP/(FP+TN))  # False positive rate

M = 100
N = 5 
s = y_probaHl
li = Dev1y
min = np.min(s)
max = np.max(s)

TPR11l = []
FPR11l = []

thresholds = np.linspace(min,max,1000)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(M): 
    for j in range(N):
      if s[i,j] >= threshold:
        if li[i] == j:
          TP+=1
        else:
          FP+=1
      else:
        if li[i] == j:
          FN+=1 
        else:
          TN+=1
  TPR11l.append(TP/(TP+FN))  # True positive rate
  FPR11l.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR11,TPR11,color='red',label='Original data')
plt.plot(FPR11P,TPR11P,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR11l,TPR11l,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

"""DET"""

y_true1 = np.zeros(M)
y_scores1 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true1[i] = 1
  y_scores1[i] = y_probaHs[i,target_class]

y_true2 = np.zeros(M)
y_scores2 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true2[i] = 1
  y_scores2[i] = y_probaHp[i,target_class]

y_true3 = np.zeros(M)
y_scores3 = np.zeros(M)

for i in range(M):
  if Dev1y[i] == target_class:
    y_true3[i] = 1
  y_scores3[i] = y_probaHl[i,target_class]

FPR1,FNR1,thresholds = det_curve(y_true1,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true2,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true3,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

"""...."""