# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-mXPCRXllDUZTaKgXY79AAqUf8i_o6GA
"""

import numpy as np
import os
import random
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
from scipy.signal import resample
from sklearn.metrics import det_curve
from sklearn.metrics import confusion_matrix

from google.colab import drive
drive.mount('/content/drive')

"""**Principal Component Analysis (PCA)**"""

# Mean estimation
def Mu(X):
  return np.sum(X,axis=0)/len(X)

# Covariance matrix estimation 
def Sigma(X,mu):
  N = len(X) 
  d = len(mu)
  X = np.reshape(X,(N,d,1))
  mu = np.reshape(mu,(d,1))
  sum = np.zeros((d,d))
  for n in range(N):
    sum += (X[n]-mu)@((X[n]-mu).T)
  return sum/(N-1)

# Principal Component Analysis
def PCA(X1,K,X2):
  mu = Mu(X1)
  sigma = Sigma(X1,mu)
  eig_vals,eig_vecs = np.linalg.eig(sigma)
  seq = np.argsort(np.absolute(eig_vals))[::-1]
  eig_vecs = eig_vecs.T
  eig_vecs = eig_vecs[seq]
  return ((np.absolute(eig_vecs)[:K])@(X1.T)).T,((np.absolute(eig_vecs)[:K])@(X2.T)).T

"""**Linear Discriminant Analysis (LDA)**"""

# Calculation of within-class scatter matrix
def SW(X,mu):
  d = len(X[0][0])
  res = np.zeros((d,d))
  for clas in range(len(X)):
    for data in X[clas]:
      res += (np.array(data)-mu[clas])@((np.array(data)-mu[clas]).T)
  return res

# Calculation of between-class scatter matrix
def SB(X,mu,mu_overall):
  d = len(mu[0])
  res = np.zeros((d,d))
  for clas in range(len(mu)):
    res += len(X[clas])*(mu[clas]-mu_overall)@((mu[clas]-mu_overall).T)
  return res

# Linear Discriminant Analysis
def LDA(X1,X1_classwise,K,X2):
  mu = []
  mu_overall = Mu(X1)
  for clas in X1_classwise:
    mu.append(Mu(clas))
  sw = SW(X1_classwise,np.array(mu))
  # To make the matrix non-singular
  for i in range(len(sw)):
    sw[i,i] += 1e-9
  sb = SB(X1_classwise,np.array(mu),mu_overall)
  eig_vals,eig_vecs = np.linalg.eig(np.linalg.inv(sw)@sb)
  seq = np.argsort(np.absolute(eig_vals))[::-1]
  eig_vecs = eig_vecs.T
  eig_vecs = eig_vecs[seq]
  return ((np.absolute(eig_vecs)[:K])@(X1.T)).T,((np.absolute(eig_vecs)[:K])@(X2.T)).T

"""**Confusion matrix**"""

def conf_matrix(tc,pc):
  n = len(np.unique(tc))
  Con_Matrix1 = np.zeros((n,n))
  for i in range(len(tc)):
    Con_Matrix1[int(tc[i])-1][int(pc[i])-1]+=1
  c = []
  r = []
  s=0
  for i in range(len(Con_Matrix1)):
    c.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1[i])*100)
    r.append(Con_Matrix1[i][i]/np.sum(Con_Matrix1.T[i])*100)
    s+=Con_Matrix1[i][i]

  r.append(s/np.sum(Con_Matrix1)*100)
    
  Con_Matrix1 = np.c_[Con_Matrix1,c]
  Con_Matrix1 = np.vstack((Con_Matrix1,r))

  classes = []
  for i in range(n):
    classes.append("class "+str(i+1))
  font = {'family': 'serif',
          'color':  'red',
          'weight': 'bold',
          'size': 16,
          }
  ax = sns.heatmap(Con_Matrix1, annot=True, fmt="g")
  ax.xaxis.set_ticklabels(classes)
  plt.title('Confusion Matrix',fontdict = font)
  ax.set_xlabel('Predicted',fontdict = font)
  ax.set_ylabel('True',fontdict = font)
  ax.yaxis.set_ticklabels(classes)
  plt.show()

"""**K Nearest Neighbour (KNN) model**"""

def comp(x):
  return x[0]

# K Nearest Neighbours
def KNN(X,K,Train_data):
  distances = []
  for clas in range(len(Train_data)):
    for example in Train_data[clas]:
      distances.append([np.linalg.norm(np.array(X)-np.array(example)),clas])
  distances.sort(key=comp)
  ans = -1
  cnts = np.zeros(len(Train_data))
  for clas in range(len(Train_data)):
    cnt = 0
    for i in range(K):
      if distances[i][1] == clas:
        cnt+=1
    if cnt > ans:
      ans = clas
    elif cnt == ans:
      if random.randint(0,1) == 1:
        ans = clas
    cnts[clas] = cnt
  return cnts,ans

"""**Synthetic dataset**"""

## Reading file into a numpy array
x1_train,x2_train,t_train = np.loadtxt("/content/drive/MyDrive/syth/train.txt", delimiter=',', unpack=True)
x1_dev,x2_dev,t_dev = np.loadtxt("/content/drive/MyDrive/syth/dev.txt", delimiter=',', unpack=True)

x_train = [x1_train,x2_train]
x_train = np.asarray(x_train)
x_train = x_train.T

x_dev = [x1_dev,x2_dev]
x_dev = np.asarray(x_dev)
x_dev = x_dev.T

# x_train = preprocessing.normalize(x_train)
# x_dev = preprocessing.normalize(x_dev)

x_dev[0]

# plt.scatter(x_dev[:,0],x_dev[:,1])
# plt.show()

x_train_PCA,x_dev_PCA = PCA(x_train,1,x_dev)

# plt.scatter(x_dev_PCA,list(np.zeros(len(x_dev_PCA))))
# plt.show()

half_train_size = 1250
half_dev_size = 500

x_train_classwise = [x_train[:half_train_size,:],x_train[half_train_size:,:]]

x_train_LDA,x_dev_LDA = LDA(x_train,x_train_classwise,1,x_dev)

plt.scatter(x_dev_LDA[0],x_dev_LDA[1])
plt.show()

x_train_PCA_classwise = [x_train_PCA[:half_train_size,:],x_train_PCA[half_train_size:,:]]

x_train_LDA_classwise = [x_train_LDA[:half_train_size,:],x_train_LDA[half_train_size:,:]]

N = len(x_dev)
C = 2
K = 8

# Original data
S1 = np.zeros((N,C))
for n in range(N):
  cnt,pred = KNN(x_dev[n],K,x_train_classwise)
  S1[n] = cnt

# Dimensionality reduction using PCA
S2 = np.zeros((N,C))
for n in range(N):
  cnt,pred = KNN(x_dev_PCA[n],K,x_train_PCA_classwise)
  S2[n] = cnt

# Dimensionality reduction using LDA
S3 = np.zeros((N,C))
for n in range(N):
  cnt,pred = KNN(x_dev_LDA[n],K,x_train_LDA_classwise)
  S3[n] = cnt

min1 = np.amin(S1)
max1 = np.amax(S1)

TPR1 = []
FPR1 = []

thresholds = np.linspace(min1,max1,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S1[i,j] >= threshold:
        if t_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if t_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR1.append(TP/(TP+FN))  # True positive rate
  FPR1.append(FP/(FP+TN))  # False positive rate

min2 = np.amin(S2)
max2 = np.amax(S2)

TPR2 = []
FPR2 = []

thresholds = np.linspace(min2,max2,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S2[i,j] >= threshold:
        if t_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if t_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR2.append(TP/(TP+FN))  # True positive rate
  FPR2.append(FP/(FP+TN))  # False positive rate

min3 = np.amin(S3)
max3 = np.amax(S3)

TPR3 = []
FPR3 = []

thresholds = np.linspace(min3,max3,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S3[i,j] >= threshold:
        if t_dev[i] == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if t_dev[i] == j+1:
          FN+=1 
        else:
          TN+=1
  TPR3.append(TP/(TP+FN))  # True positive rate
  FPR3.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR1,TPR1,color='red',label='Original data')
plt.plot(FPR2,TPR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,TPR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

target_class = 1

y_true = np.zeros(N)
y_scores1 = np.zeros(N)
for i in range(N):
  if t_dev[i] == target_class:
    y_true[i] = 1
  y_scores1[i] = S1[i,target_class-1]

y_scores2 = np.zeros(N)
for i in range(N):
  y_scores2[i] = S2[i,target_class-1]

y_scores3 = np.zeros(N)
for i in range(N):
  y_scores3[i] = S3[i,target_class-1]

FPR1,FNR1,thresholds = det_curve(y_true,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

groudtruth = [1]*500 + [2]*500
y_pred = np.argmax(S3,1)+1
conf_matrix(groudtruth,y_pred)

"""**Image dataset**"""

## Reading file into a numpy array

Train_data = []
Dev_data = []

X=[]
os.chdir('/content/drive/MyDrive/Features/coast/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/coast/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/coast/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/coast/train'}/{file}" 
    Y.append(np.loadtxt(file_path)) 
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/forest/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/forest/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/forest/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/forest/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/highway/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/highway/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/highway/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/highway/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/mountain/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/mountain/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/mountain/train')
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/mountain/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

X=[]
os.chdir('/content/drive/MyDrive/Features/opencountry/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/opencountry/dev'}/{file}" 
    X.append(np.loadtxt(file_path))
Dev_data.append(X)

Y=[]
os.chdir('/content/drive/MyDrive/Features/opencountry/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".jpg_color_edh_entropy"):
    file_path = f"{'/content/drive/MyDrive/Features/opencountry/train'}/{file}" 
    Y.append(np.loadtxt(file_path))
Train_data.append(Y)

Train_data1 = []
for clas in Train_data:
  for image in clas:
    temp=[]
    for block in image:
      temp += list(block)
    Train_data1.append(temp)

Dev_data1 = []
for clas in Dev_data:
  for image in clas:
    temp=[]
    for block in image:
      temp += list(block)
    Dev_data1.append(temp)

Train_data1 = preprocessing.normalize(Train_data1)

Dev_data1 = preprocessing.normalize(Dev_data1)

Train_data1_classwise = []
for clas in Train_data:
  temp1=[]
  for img in clas:
    temp2=[]
    for block in img:
      temp2 += list(block)
    temp1.append(temp2)
  Train_data1_classwise.append(temp1)

for i in range(5):
  Train_data1_classwise[i] = preprocessing.normalize(Train_data1_classwise[i])

K = 20

Train_data_PCA,Dev_data_PCA = PCA(np.array(Train_data1),K,np.array(Dev_data1))

Train_data_PCA_classwise = [Train_data_PCA[0:251],Train_data_PCA[251:480],Train_data_PCA[480:662],Train_data_PCA[662:923],Train_data_PCA[923:]]

Train_data_LDA,Dev_data_LDA = LDA(np.array(Train_data1),Train_data1_classwise,K,np.array(Dev_data1))

Train_data_LDA_classwise = [Train_data_LDA[0:251],Train_data_LDA[251:480],Train_data_LDA[480:662],Train_data_LDA[662:923],Train_data_LDA[923:]]

N = len(Dev_data1)
C = 5
K = 7

# Original data
S1 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data1[n],K,Train_data1_classwise)
  S1[n] = np.array(score)

# Dimensionality reduction using PCA
S2 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data_PCA[n],K,Train_data_PCA_classwise)
  S2[n] = np.array(score)

# Dimensionality reduction using LDA
S3 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data_LDA[n],K,Train_data_LDA_classwise)
  S3[n] = np.array(score)

def groundtruth_dev(i):
  if i<=73:
    return 1
  elif i<=139:
    return 2
  elif i<=191:
    return 3
  elif i<=266:
    return 4
  else:
    return 5

min1 = np.amin(S1)
max1 = np.amax(S1)

TPR1 = []
FPR1 = []

thresholds = np.linspace(min1,max1,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S1[i,j] >= threshold:
        if groundtruth_dev(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR1.append(TP/(TP+FN))  # True positive rate
  FPR1.append(FP/(FP+TN))  # False positive rate

min2 = np.amin(S2)
max2 = np.amax(S2)

TPR2 = []
FPR2 = []

thresholds = np.linspace(min2,max2,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S2[i,j] >= threshold:
        if groundtruth_dev(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR2.append(TP/(TP+FN))  # True positive rate
  FPR2.append(FP/(FP+TN))  # False positive rate

min3 = np.amin(S3)
max3 = np.amax(S3)

TPR3 = []
FPR3 = []

thresholds = np.linspace(min3,max3,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S3[i,j] >= threshold:
        if groundtruth_dev(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR3.append(TP/(TP+FN))  # True positive rate
  FPR3.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR1,TPR1,color='red',label='Original data')
plt.plot(FPR2,TPR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,TPR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

target_class = 1

y_true = np.zeros(N)
y_scores1 = np.zeros(N)
for i in range(N):
  if groundtruth_dev(i) == target_class:
    y_true[i] = 1
  y_scores1[i] = S1[i,target_class-1]

y_scores2 = np.zeros(N)
for i in range(N):
  y_scores2[i] = S2[i,target_class-1]

y_scores3 = np.zeros(N)
for i in range(N):
  y_scores3[i] = S3[i,target_class-1]

FPR1,FNR1,thresholds = det_curve(y_true,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

groudtruth = [1]*73 + [2]*66 + [3]*52 + [4]*75 + [5]*82
y_pred = np.argmax(S1,1)+1
conf_matrix(groudtruth,y_pred)

"""**Isolated digits dataset**"""

## Reading file into a numpy array

Train_data = []
Dev_data = []

X=[]
os.chdir('/content/drive/MyDrive/3/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/3/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/3/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/3/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))      
Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/4/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/4/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/4/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/4/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/5/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/5/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/5/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/5/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/7/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/7/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/7/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/7/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Train_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/o/dev')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/o/dev'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Dev_data.append(X)

X=[]
os.chdir('/content/drive/MyDrive/o/train')
# iterate through all file
for file in os.listdir():
  if file.endswith(".mfcc"):
    file_path = f"{'/content/drive/MyDrive/o/train'}/{file}" 
    X.append(np.loadtxt(file_path, skiprows=1))
Train_data.append(X)

frame_size = 38

max_no_of_frames = 0

for clas in Train_data:
  for example in clas:
    if max_no_of_frames < len(example):
      max_no_of_frames = len(example)

for clas in Dev_data:
  for example in clas:
    if max_no_of_frames < len(example):
      max_no_of_frames = len(example)

total_size = max_no_of_frames*frame_size

Train_data1=[]
for clas in Train_data:
  for example in clas:
    # temp=[]
    # for frame in example:
    #   temp += list(frame)
    # while len(temp) < total_size:
    #   temp.append(0)
    sample = resample(example,max_no_of_frames)
    res = []
    for frame in sample:
      res += list(frame)    
    Train_data1.append(res)

np.array(Train_data1).shape

total_size

Dev_data1=[]
for clas in Dev_data:
  for example in clas:
    # temp=[]
    # for frame in example:
    #   temp += list(frame)
    # while len(temp) < total_size:
    #   temp.append(0)
    # Dev_data1.append(temp)
    sample = resample(example,max_no_of_frames)
    res = []
    for frame in sample:
      res += list(frame)    
    Dev_data1.append(res)

np.array(Dev_data1).shape

Train_data1 = preprocessing.normalize(Train_data1)

Dev_data1 = preprocessing.normalize(Dev_data1)

Train_data1_classwise = [Train_data1[0:39],Train_data1[39:78],Train_data1[78:117],Train_data1[117:156],Train_data1[156:]]

for i in range(5):
  Train_data1_classwise[i] = preprocessing.normalize(Train_data1_classwise[i])

K = 100

Train_data_PCA,Dev_data_PCA = PCA(np.array(Train_data1),K,np.array(Dev_data1))

Train_data_PCA_classwise = [Train_data_PCA[0:39],Train_data_PCA[39:78],Train_data_PCA[78:117],Train_data_PCA[117:156],Train_data_PCA[156:]]

Train_data_LDA,Dev_data_LDA = LDA(np.array(Train_data1),Train_data1_classwise,K,np.array(Dev_data1))

Train_data_LDA_classwise = [Train_data_LDA[0:39],Train_data_PCA[39:78],Train_data_PCA[78:117],Train_data_PCA[117:156],Train_data_PCA[156:]]

N = len(Dev_data1)
C = 5
K = 20

S1 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data1[n],K,Train_data1_classwise)
  S1[n] = np.array(score)

S2 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data_PCA[n],K,Train_data_PCA_classwise)
  S2[n] = np.array(score)

S3 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data_LDA[n],K,Train_data_LDA_classwise)
  S3[n] = np.array(score)

def groundtruth_dev_isodig(i):
  if i<12:
    return 1
  elif i<24:
    return 2
  elif i<36:
    return 3
  elif i<48:
    return 4
  else:
    return 5

min1 = np.amin(S1)
max1 = np.amax(S1)

TPR1 = []
FPR1 = []

thresholds = np.linspace(min1,max1,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S1[i,j] >= threshold:
        if groundtruth_dev_isodig(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_isodig(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR1.append(TP/(TP+FN))  # True positive rate
  FPR1.append(FP/(FP+TN))  # False positive rate

min2 = np.amin(S2)
max2 = np.amax(S2)

TPR2 = []
FPR2 = []

thresholds = np.linspace(min2,max2,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S2[i,j] >= threshold:
        if groundtruth_dev_isodig(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_isodig(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR2.append(TP/(TP+FN))  # True positive rate
  FPR2.append(FP/(FP+TN))  # False positive rate

min3 = np.amin(S3)
max3 = np.amax(S3)

TPR3 = []
FPR3 = []

thresholds = np.linspace(min3,max3,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S3[i,j] >= threshold:
        if groundtruth_dev_isodig(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_isodig(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR3.append(TP/(TP+FN))  # True positive rate
  FPR3.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR1,TPR1,color='red',label='Original data')
plt.plot(FPR2,TPR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,TPR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

target_class = 1

y_true = np.zeros(N)
y_scores1 = np.zeros(N)
for i in range(N):
  if groundtruth_dev_isodig(i) == target_class:
    y_true[i] = 1
  y_scores1[i] = S1[i,target_class-1]

y_scores2 = np.zeros(N)
for i in range(N):
  y_scores2[i] = S2[i,target_class-1]

y_scores3 = np.zeros(N)
for i in range(N):
  y_scores3[i] = S3[i,target_class-1]

FPR1,FNR1,thresholds = det_curve(y_true,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

groudtruth = [1]*12 + [2]*12 + [3]*12 + [4]*12 + [5]*12
y_pred = np.argmax(S1,1)+1
conf_matrix(groudtruth,y_pred)

"""**Handwritten character dataset**"""

Train_data_digits = []

X1=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X1.append(K)
Train_data_digits.append(X1)

X2=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X2.append(K)
Train_data_digits.append(X2)

X3=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X3.append(K)
Train_data_digits.append(X3)

X4=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X4.append(K)
Train_data_digits.append(X4)

X5=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/train')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/train'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    X5.append(K)
Train_data_digits.append(X5)

Dev1=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/a/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/a/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev1.append(K)

Dev2=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/ai/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/ai/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev2.append(K)

Dev3=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/bA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/bA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev3.append(K)

Dev4=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/chA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/chA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev4.append(K)

Dev5=[]
os.chdir('/content/drive/MyDrive/Handwriting_Data/dA/dev')
for file in os.listdir():
  # Check whether file is in text format or not
  if file.endswith(".txt"):
    file_path = f"{'/content/drive/MyDrive/Handwriting_Data/dA/dev'}/{file}" 
    M = np.loadtxt(file_path)
    K = []
    for i in range(1,len(M)-4,2):
      K.append([M[i],M[i+1],(M[i+3]-M[i+1])/(M[i+2]-M[i]+10**-3)])
    for i in range(len(M)-3,len(M)-1):
      K.append([M[i],M[i+1],(M[i-3]-M[i-1])/(M[i-2]-M[i]+10**-3)])
    K = np.asarray(K)
    Dev5.append(K)

Dev_data_digits = [Dev1,Dev2,Dev3,Dev4,Dev5]

frame_size = 3

max_no_of_frames = 0

for clas in Train_data_digits:
  for example in clas:
    if max_no_of_frames < len(example):
      max_no_of_frames = len(example)

for clas in Dev_data_digits:
  for example in clas:
    if max_no_of_frames < len(example):
      max_no_of_frames = len(example)

total_size = max_no_of_frames*frame_size

Train_data1=[]
for clas in Train_data_digits:
  for eg in clas:
    # temp=[]
    # for frame in eg:
    #   temp += list(frame)
    # while len(temp) < total_size:
    #   temp.append(0)
    # Train_data1.append(temp)
    sample = resample(eg,max_no_of_frames)
    res = []
    for frame in sample:
      res += list(frame)    
    Train_data1.append(res)

Dev_data1=[]
for clas in Dev_data_digits:
  for eg in clas:
    # temp=[]
    # for frame in eg:
    #   temp += list(frame)
    # while len(temp) < total_size:
    #   temp.append(0)
    # Dev_data1.append(temp)
    sample = resample(eg,max_no_of_frames)
    res = []
    for frame in sample:
      res += list(frame)    
    Dev_data1.append(res)

Train_data1 = preprocessing.normalize(Train_data1)

Dev_data1 = preprocessing.normalize(Dev_data1)

Train_data1_classwise = [Train_data1[0:69],Train_data1[69:139],Train_data1[139:206],Train_data1[206:276],Train_data1[276:]]

K = 10

Train_data_PCA,Dev_data_PCA = PCA(np.array(Train_data1),K,np.array(Dev_data1))

Train_data_PCA_classwise = [Train_data_PCA[0:69],Train_data_PCA[69:139],Train_data_PCA[139:206],Train_data_PCA[206:276],Train_data_PCA[276:]]

Train_data_LDA,Dev_data_LDA = LDA(np.array(Train_data1),Train_data1_classwise,K,np.array(Dev_data1))

Train_data_LDA_classwise = [Train_data_LDA[0:69],Train_data_LDA[69:139],Train_data_LDA[139:206],Train_data_LDA[206:276],Train_data_LDA[276:]]

N = len(Dev_data1)
C = 5
K = 20

S1 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data1[n],K,Train_data1_classwise)
  S1[n] = np.array(score)

S2 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data_PCA[n],K,Train_data_PCA_classwise)
  S2[n] = np.array(score)

S3 = np.zeros((N,C))
for n in range(N):
  score,pred = KNN(Dev_data_LDA[n],K,Train_data_LDA_classwise)
  S3[n] = np.array(score)

def groundtruth_dev_handwritten(i):
  if i<20:
    return 1
  elif i<40:
    return 2
  elif i<60:
    return 3
  elif i<80:
    return 4
  else:
    return 5

min1 = np.amin(S1)
max1 = np.amax(S1)

TPR1 = []
FPR1 = []

thresholds = np.linspace(min1,max1,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S1[i,j] >= threshold:
        if groundtruth_dev_handwritten(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_handwritten(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR1.append(TP/(TP+FN))  # True positive rate
  FPR1.append(FP/(FP+TN))  # False positive rate

min2 = np.amin(S2)
max2 = np.amax(S2)

TPR2 = []
FPR2 = []

thresholds = np.linspace(min2,max2,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S2[i,j] >= threshold:
        if groundtruth_dev_handwritten(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_handwritten(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR2.append(TP/(TP+FN))  # True positive rate
  FPR2.append(FP/(FP+TN))  # False positive rate

min3 = np.amin(S3)
max3 = np.amax(S3)

TPR3 = []
FPR3 = []

thresholds = np.linspace(min3,max3,100)

for threshold in thresholds:
  TP = FP = TN = FN = 0
  for i in range(N): 
    for j in range(C):
      if S3[i,j] >= threshold:
        if groundtruth_dev_handwritten(i) == j+1:
          TP+=1
        else:
          FP+=1
      else:
        if groundtruth_dev_handwritten(i) == j+1:
          FN+=1 
        else:
          TN+=1
  TPR3.append(TP/(TP+FN))  # True positive rate
  FPR3.append(FP/(FP+TN))  # False positive rate

plt.plot(FPR1,TPR1,color='red',label='Original data')
plt.plot(FPR2,TPR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,TPR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

target_class = 1

y_true = np.zeros(N)
y_scores1 = np.zeros(N)
for i in range(N):
  if groundtruth_dev_handwritten(i) == target_class:
    y_true[i] = 1
  y_scores1[i] = S1[i,target_class-1]

y_scores2 = np.zeros(N)
for i in range(N):
  y_scores2[i] = S2[i,target_class-1]

y_scores3 = np.zeros(N)
for i in range(N):
  y_scores3[i] = S3[i,target_class-1]

FPR1,FNR1,thresholds = det_curve(y_true,y_scores1)
FPR2,FNR2,thresholds = det_curve(y_true,y_scores2)
FPR3,FNR3,thresholds = det_curve(y_true,y_scores3)

plt.plot(FPR1,FNR1,color='red',label='Original data')
plt.plot(FPR2,FNR2,color='blue',label='Dimensionality reduction using PCA')
plt.plot(FPR3,FNR3,color='green',label='Dimensionality reduction using LDA')

# Naming the x-axis, y-axis and the whole graph
plt.xlabel("False Alarm Rate")
plt.ylabel("Missed Detection Rate")
plt.title("DET curve")
  
# Adding legend, which helps us recognize the curve according to it's color
plt.legend()
  
# To load the display window
plt.show()

groudtruth = [1]*20 + [2]*20 + [3]*20 + [4]*20 + [5]*20
y_pred = np.argmax(S3,1)+1
conf_matrix(groudtruth,y_pred)